### ISSUE TITLE
[B16] Opening Research Table GUI near Crimson Portal crashes game

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#1023]
as title.
Not world breaking, luckily.

**Comment by F9Alejandro** [comment]
Do you have a crash log that can help provide more insight of what is happening in the background as the crash occurs?

**Comment by MalkContent** [comment]
no, and can't make one right now. if you can, hop into the game real quick, spawn the portal and open the research table in creative

**Comment by MalkContent** [comment]
<details><summary>Crashlog (clickme):</summary><p>
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/17/18 2:36 AM
Description: Rendering screen

java.lang.ClassCastException: java.lang.Class cannot be cast to net.minecraft.block.Block
	at thaumcraft.client.gui.GuiResearchTable.func_146976_a(GuiResearchTable.java:262)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at thaumcraft.client.gui.GuiResearchTable.func_73863_a(GuiResearchTable.java:111)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.gui.GuiResearchTable.func_146976_a(GuiResearchTable.java:262)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at thaumcraft.client.gui.GuiResearchTable.func_73863_a(GuiResearchTable.java:111)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)

-- Screen render details --
Details:
	Screen name: thaumcraft.client.gui.GuiResearchTable
	Mouse location: Scaled: (256, 138). Absolute: (1280, 688)
	Screen size: Scaled: (512, 276). Absolute: (2560, 1377). Scale factor of 5

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MalkContent'/663, l='MpServer', x=-69.46, y=64.00, z=-464.74]]
	Chunk stats: MultiplayerChunkCache: 575, 575
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-82,64,-465), Chunk: (at 14,4,15 in -6,-30; contains blocks -96,0,-480 to -81,255,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1253 game time, 1253 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 94 total; [EntityChicken['Chicken'/4, l='MpServer', x=-141.13, y=81.00, z=-507.51], EntityChicken['Chicken'/5, l='MpServer', x=-146.50, y=76.00, z=-513.50], EntitySheep['Sheep'/9, l='MpServer', x=-95.24, y=66.00, z=-454.54], EntitySheep['Sheep'/10, l='MpServer', x=-84.78, y=66.00, z=-455.55], EntitySheep['Sheep'/11, l='MpServer', x=-103.21, y=67.00, z=-456.50], EntitySheep['Sheep'/12, l='MpServer', x=-105.34, y=68.00, z=-462.24], EntitySheep['Sheep'/13, l='MpServer', x=-93.50, y=65.00, z=-454.50], EntitySheep['Sheep'/14, l='MpServer', x=-92.79, y=66.00, z=-442.84], EntitySheep['Sheep'/15, l='MpServer', x=-87.25, y=66.00, z=-453.49], EntitySheep['Sheep'/16, l='MpServer', x=-88.52, y=66.10, z=-449.61], EntitySheep['Sheep'/19, l='MpServer', x=-53.50, y=63.00, z=-521.50], EntitySheep['Sheep'/20, l='MpServer', x=-52.50, y=63.00, z=-521.50], EntitySheep['Sheep'/21, l='MpServer', x=-41.81, y=63.00, z=-512.80], EntitySheep['Sheep'/22, l='MpServer', x=-55.50, y=63.00, z=-520.50], EntitySheep['Sheep'/31, l='MpServer', x=-2.50, y=68.00, z=-531.50], EntitySheep['Sheep'/32, l='MpServer', x=-1.45, y=68.00, z=-531.50], EntitySheep['Sheep'/33, l='MpServer', x=-1.53, y=68.00, z=-536.19], EntitySheep['Sheep'/34, l='MpServer', x=3.50, y=68.00, z=-529.50], EntityFallingBlock['Falling Block'/122, l='MpServer', x=-179.50, y=17.00, z=-624.50], EntityCreeper['Creeper'/2750, l='MpServer', x=-64.85, y=43.00, z=-450.50], EntityCreeper['Creeper'/2751, l='MpServer', x=-72.17, y=47.00, z=-450.51], EntityZombie['Zombie'/2752, l='MpServer', x=-81.11, y=47.00, z=-451.58], EntitySkeleton['Skeleton'/2789, l='MpServer', x=-56.22, y=48.00, z=-482.50], EntitySkeleton['Skeleton'/2792, l='MpServer', x=-6.50, y=19.00, z=-506.50], EntityBat['Bat'/2838, l='MpServer', x=-137.95, y=21.07, z=-480.24], EntitySkeleton['Skeleton'/2929, l='MpServer', x=-51.50, y=19.00, z=-527.50], EntityItem['item.tile.gravel'/2937, l='MpServer', x=-25.13, y=36.00, z=-487.81], EntitySpider['Spider'/2952, l='MpServer', x=-48.50, y=14.00, z=-521.50], EntityZombie['Zombie'/3268, l='MpServer', x=-70.50, y=12.00, z=-516.50], EntitySkeleton['Skeleton'/3273, l='MpServer', x=-84.50, y=49.00, z=-493.50], EntityCreeper['Creeper'/3277, l='MpServer', x=-81.50, y=49.00, z=-493.50], EntitySkeleton['Skeleton'/3278, l='MpServer', x=-120.50, y=38.00, z=-476.50], EntitySkeleton['Skeleton'/3279, l='MpServer', x=-122.50, y=38.00, z=-473.50], EntityZombie['Zombie'/3284, l='MpServer', x=-38.50, y=13.00, z=-484.50], EntityZombie['Zombie'/1264, l='MpServer', x=-93.77, y=37.00, z=-535.49], EntityZombie['Zombie'/3313, l='MpServer', x=-86.50, y=33.00, z=-423.50], EntityWitch['Witch'/3323, l='MpServer', x=-134.50, y=20.00, z=-478.50], EntityCreeper['Creeper'/3324, l='MpServer', x=-135.50, y=20.00, z=-477.50], EntityCreeper['Creeper'/3325, l='MpServer', x=-130.52, y=20.00, z=-484.18], EntityCreeper['Creeper'/3338, l='MpServer', x=-71.50, y=12.00, z=-514.50], EntityCreeper['Creeper'/3363, l='MpServer', x=-54.50, y=45.00, z=-501.50], EntitySpider['Spider'/3382, l='MpServer', x=-128.50, y=20.00, z=-483.50], EntitySquid['Squid'/1343, l='MpServer', x=-131.01, y=59.95, z=-452.36], EntitySquid['Squid'/1346, l='MpServer', x=-128.60, y=62.36, z=-446.07], EntitySquid['Squid'/1347, l='MpServer', x=-60.67, y=49.00, z=-447.67], EntitySquid['Squid'/1348, l='MpServer', x=-51.90, y=56.41, z=-458.62], EntitySquid['Squid'/1349, l='MpServer', x=-51.07, y=49.00, z=-441.40], EntitySpider['Spider'/3399, l='MpServer', x=-48.04, y=43.00, z=-465.97], EntitySquid['Squid'/1357, l='MpServer', x=-5.48, y=57.77, z=-413.52], EntitySquid['Squid'/1359, l='MpServer', x=-13.02, y=52.90, z=-410.97], EntitySquid['Squid'/1361, l='MpServer', x=-130.76, y=48.05, z=-455.60], EntitySquid['Squid'/1364, l='MpServer', x=-132.98, y=49.10, z=-452.86], EntitySquid['Squid'/1375, l='MpServer', x=-103.62, y=59.65, z=-410.27], EntitySquid['Squid'/1378, l='MpServer', x=-98.44, y=60.72, z=-420.05], EntitySpider['Spider'/3427, l='MpServer', x=-56.50, y=45.00, z=-500.50], EntityCreeper['Creeper'/3432, l='MpServer', x=-46.50, y=42.00, z=-498.50], EntitySkeleton['Skeleton'/3446, l='MpServer', x=-22.50, y=28.00, z=-508.50], EntityCreeper['Creeper'/3454, l='MpServer', x=-17.50, y=15.00, z=-414.50], EntitySkeleton['Skeleton'/3456, l='MpServer', x=-28.50, y=28.00, z=-495.50], EntityCreeper['Creeper'/3468, l='MpServer', x=-42.50, y=13.00, z=-460.20], EntityZombie['Zombie'/3492, l='MpServer', x=-95.50, y=37.00, z=-533.50], EntityBat['Bat'/1461, l='MpServer', x=-60.75, y=22.10, z=-474.75], EntityBat['Bat'/1464, l='MpServer', x=-4.25, y=14.46, z=-434.50], EntityCreeper['Creeper'/1501, l='MpServer', x=-86.44, y=46.00, z=-487.81], EntityPlayerSP['MalkContent'/663, l='MpServer', x=-69.46, y=64.00, z=-464.74], EntityZombie['Zombie'/3585, l='MpServer', x=-72.50, y=21.00, z=-542.50], EntityZombie['Zombie'/3596, l='MpServer', x=-65.50, y=21.00, z=-398.50], EntityZombie['Zombie'/3597, l='MpServer', x=-68.50, y=21.00, z=-397.50], EntitySkeleton['Skeleton'/3634, l='MpServer', x=-44.65, y=14.00, z=-532.66], EntitySkeleton['Skeleton'/3635, l='MpServer', x=-49.71, y=20.00, z=-519.48], EntitySkeleton['Skeleton'/3636, l='MpServer', x=-52.49, y=19.00, z=-522.78], EntityCreeper['Creeper'/3637, l='MpServer', x=-52.20, y=19.00, z=-519.56], EntitySkeleton['Skeleton'/3658, l='MpServer', x=-28.50, y=44.00, z=-506.50], EntitySkeleton['Skeleton'/3659, l='MpServer', x=-27.50, y=44.00, z=-505.50], EntitySkeleton['Skeleton'/3660, l='MpServer', x=-28.50, y=44.00, z=-504.50], EntitySkeleton['Skeleton'/3661, l='MpServer', x=-30.50, y=44.00, z=-503.50], EntityBat['Bat'/3671, l='MpServer', x=-136.36, y=31.02, z=-498.67], EntityBat['Bat'/3720, l='MpServer', x=-44.75, y=44.10, z=-468.51], EntityBat['Bat'/3757, l='MpServer', x=-76.30, y=26.71, z=-395.81], EntityBat['Bat'/3761, l='MpServer', x=-30.46, y=24.92, z=-488.26], EntitySkeleton['Skeleton'/3765, l='MpServer', x=-5.50, y=14.00, z=-448.50], EntitySkeleton['Skeleton'/3778, l='MpServer', x=-79.21, y=47.00, z=-479.63], EntitySpider['Spider'/3786, l='MpServer', x=-41.50, y=16.00, z=-540.50], EntityBat['Bat'/3815, l='MpServer', x=10.15, y=57.46, z=-538.33], EntitySkeleton['Skeleton'/3835, l='MpServer', x=-22.50, y=44.00, z=-503.50], EntityZombie['Zombie'/3873, l='MpServer', x=-37.50, y=28.00, z=-483.50], EntitySkeleton['Skeleton'/3895, l='MpServer', x=-33.50, y=16.00, z=-524.50], EntityCreeper['Creeper'/3897, l='MpServer', x=-30.50, y=28.00, z=-506.50], EntityCreeper['Creeper'/3898, l='MpServer', x=-33.50, y=28.00, z=-510.50], EntityCultistPortalLesser['Lesser Crimson Portal'/3903, l='MpServer', x=-67.50, y=64.00, z=-466.50], EntityBat['Bat'/3919, l='MpServer', x=-53.29, y=48.52, z=-480.80], EntityCultistKnight['Crimson Knight'/3925, l='MpServer', x=-66.80, y=64.00, z=-466.13], EntitySkeleton['Skeleton'/3963, l='MpServer', x=-88.50, y=22.00, z=-505.50], EntityCultistKnight['Crimson Knight'/3965, l='MpServer', x=-66.99, y=64.25, z=-466.67]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4437970904 bytes (4232 MB) / 5100273664 bytes (4864 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 10 total; -Xmx8192m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.4.2708.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.4.2708 | forge-1.12.2-14.23.4.2708.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCHIJAAAA | jei        | 4.10.0.198   | jei_1.12.2-4.10.0.198.jar        | None                                     |
	| UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar      | None                                     |
	| UCHIJAAAA | thaumcraft | 6.1.BETA16   | Thaumcraft-1.12.2-6.1.BETA16.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 980/PCIe/SSE2'
	Launched Version: forge-14.23.4.2708
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
</p></details>

![grafik](https://user-images.githubusercontent.com/7753414/41503533-3c56f044-71d7-11e8-8a30-065dcb3c7f1a.png)
