### ISSUE TITLE
what is is?

### ISSUE THREAD

**Issue by prokopiy** [Azanor/thaumcraft-beta#1039]
Thaumcraft-1.12.2-6.1.BETA16.jar

[20:58:41] [Server thread/ERROR]: Error while creating CraftingInventoryLensImpl for thaumcraft.common.container.ContainerArcaneWorkbench
java.lang.ClassCastException: org.spongepowered.common.item.inventory.lens.impl.slots.SlotLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.slots.CraftingOutputSlotLens
   at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:55) ~[CraftingInventoryLensImpl.class:1.12.2-2655-7.1.0-BETA-3105]
   at org.spongepowered.common.item.inventory.lens.impl.comp.CraftingInventoryLensImpl.<init>(CraftingInventoryLensImpl.java:49) ~[CraftingInventoryLensImpl.class:1.12.2-2655-7.1.0-BETA-3105]
   at org.spongepowered.common.item.inventory.util.ContainerUtil.generateLens(ContainerUtil.java:295) [ContainerUtil.class:1.12.2-2655-7.1.0-BETA-3105]
   at org.spongepowered.common.item.inventory.util.ContainerUtil.getLens(ContainerUtil.java:222) [ContainerUtil.class:1.12.2-2655-7.1.0-BETA-3105]
   at net.minecraft.inventory.Container.spongeInit(Container.java:1019) [afr.class:?]
   at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:1076) [afr.class:?]
   at net.minecraft.inventory.Container.func_75142_b(Container.java:1071) [afr.class:?]
   at thaumcraft.common.container.ContainerArcaneWorkbench.func_75142_b(ContainerArcaneWorkbench.java:103) [ContainerArcaneWorkbench.class:?]
   at net.minecraft.inventory.Container.func_75132_a(Container.java:1058) [afr.class:?]
   at thaumcraft.common.container.ContainerArcaneWorkbench.func_75132_a(ContainerArcaneWorkbench.java:92) [ContainerArcaneWorkbench.class:?]
   at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:101) [FMLNetworkHandler.class:?]
   at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) [aed.class:?]
   at thaumcraft.common.blocks.crafting.BlockArcaneWorkbench.func_180639_a(BlockArcaneWorkbench.java:43) [BlockArcaneWorkbench.class:?]
   at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1268) [or.class:?]
   at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zjb000(NetHandlerPlayServer.java:2893) [pa.class:?]
   at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
   at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
   at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
   at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3105]
   at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlh000(SourceFile:539) [hv$1.class:?]
   at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
   at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
   at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
   at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3105]
   at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3975) [MinecraftServer.class:?]
   at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
   at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
   at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
   at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by Azanor** [comment]
This is a bug with  CraftingInventoryLensImpl, not thaumcraft.
