### ISSUE TITLE
[B16] Crash server

### ISSUE THREAD

**Issue by MaXoNFeRuS** [Azanor/thaumcraft-beta#1076]
How to fix this crash?

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b155.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3242.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 29.06.18 19:33
Description: Exception in server tick loop

java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to thaumcraft.common.items.casters.ItemFocusPouch
	at thaumcraft.common.container.ContainerFocusPouch.func_75134_a(ContainerFocusPouch.java:127)
	at net.minecraft.entity.player.EntityPlayer.redirect$onOnContainerClosed$zgl000(EntityPlayer.java:43371)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1511)
	at net.minecraft.world.World.func_72900_e(World.java:1242)
	at net.minecraft.server.management.PlayerList.redirect$onPlayerRemoveFromWorldFromDisconnect$zjg000(PlayerList.java:2020)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:412)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.container.ContainerFocusPouch.func_75134_a(ContainerFocusPouch.java:127)
	at net.minecraft.entity.player.EntityPlayer.redirect$onOnContainerClosed$zgl000(EntityPlayer.java:43371)
	at net.minecraft.entity.player.EntityPlayer.func_70106_y(EntityPlayer.java:1511)
	at net.minecraft.world.World.func_72900_e(World.java:1242)
	at net.minecraft.server.management.PlayerList.redirect$onPlayerRemoveFromWorldFromDisconnect$zjg000(PlayerList.java:2020)
	at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:412)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:457)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:213)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjf000(MinecraftServer.java:3997)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 645324656 bytes (615 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 7 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xms1G -XX:MaxPermSize=512M
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                     | Source                                                         | Signature                                |
	|:--------- |:------------------------- |:--------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                      | minecraft.jar                                                  | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                        | minecraft.jar                                                  | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99                   | forge.jar                                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.4.2705                | forge.jar                                                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | spongeapi                 | 7.1.0-SNAPSHOT-f28d4ba      | spongeforge-1.12.2-2705-7.1.0-BETA-3242.jar                    | None                                     |
	| UCHIJAAAA | sponge                    | 1.12.2-2705-7.1.0-BETA-3242 | spongeforge-1.12.2-2705-7.1.0-BETA-3242.jar                    | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UCHIJAAAA | actionbroadcaster         | 0.7.1                       | ActionBroadcaster.jar                                          | None                                     |
	| UCHIJAAAA | actionhealth              | 1.0                         | ActionHealth-1.1.jar                                           | None                                     |
	| UCHIJAAAA | ic2                       | 2.8.86-ex112                | industrialcraft-2-2.8.86-ex112.jar                             | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | advanced_solar_panels     | 4.2.0                       | Advanced+Solar+Panels-4.2.0.jar                                | None                                     |
	| UCHIJAAAA | appliedenergistics2       | rv5-stable-11               | appliedenergistics2-rv5-stable-11.jar                          | None                                     |
	| UCHIJAAAA | aroma1997core             | 2.0.0.0.b155                | Aroma1997Core-1.12.2-2.0.0.0.b155.jar                          | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aroma1997sdimension       | 2.0.0.2.b69                 | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b69.jar            | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | baubles                   | 1.5.2                       | Baubles-1.12-1.5.2.jar                                         | None                                     |
	| UCHIJAAAA | bibliocraft               | 2.4.4                       | BiblioCraft[v2.4.4][MC1.12.2].jar                              | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.1.8.341                   | CodeChickenLib-1.12.2-3.1.8.341-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux              | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore              | 2.4.2                       | BrandonsCore-1.12-2.4.2.157-universal.jar                      | None                                     |
	| UCHIJAAAA | catclearlag               | 0.8                         | CatClearLag-0.8.jar                                            | None                                     |
	| UCHIJAAAA | cofhcore                  | 4.5.2                       | CoFHCore-1.12.2-4.5.2.19-universal.jar                         | None                                     |
	| UCHIJAAAA | cofhworld                 | 1.2.0                       | CoFHWorld-1.12.2-1.2.0.5-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalfoundation         | 2.5.0                       | ThermalFoundation-1.12.2-2.5.0.19-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | draconicevolution         | 2.3.11                      | Draconic-Evolution-1.12-2.3.11.290-universal.jar               | None                                     |
	| UCHIJAAAA | dynmap                    | 2.6-beta-1-3                | Dynmap-2.6-beta-1-forge-1.12.jar                               | None                                     |
	| UCHIJAAAA | griefprevention           | 4.3.0                       | griefprevention-1.12.2-4.3.0.628.jar                           | None                                     |
	| UCHIJAAAA | dynmapgriefprevention     |                             | Dynmap-GriefPrevention-1.0-Forge.jar                           | None                                     |
	| UCHIJAAAA | nucleus                   | 1.4.2-S7.0                  | Nucleus-1.4.2-S7.0-MC1.12.2-plugin.jar                         | None                                     |
	| UCHIJAAAA | dynmap-nucleus            | 0.1                         | Dynmap-Nucleus-0.3-S7.0.jar                                    | None                                     |
	| UCHIJAAAA | endercore                 | 1.12.2-0.5.31               | EnderCore-1.12.2-0.5.31.jar                                    | None                                     |
	| UCHIJAAAA | extrautils2               | 1.0                         | extrautils2-1.12-1.7.6.jar                                     | None                                     |
	| UCHIJAAAA | fastasyncworldedit        | development                 | FastAsyncWorldEdit-sponge112-18.06.18-c4d3735-1143-20.1.13.jar | None                                     |
	| UCHIJAAAA | worldedit                 |                             | FastAsyncWorldEdit-sponge112-18.06.18-c4d3735-1143-20.1.13.jar | None                                     |
	| UCHIJAAAA | jei                       | 4.10.0.199                  | jei_1.12.2-4.10.0.199.jar                                      | None                                     |
	| UCHIJAAAA | forestry                  | 5.8.0.306                   | forestry_1.12.2-5.8.0.306.jar                                  | None                                     |
	| UCHIJAAAA | forgemultipartcbe         | 2.4.2.58                    | ForgeMultipart-1.12.2-2.4.2.58-universal.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe             | 2.4.2.58                    | ForgeMultipart-1.12.2-2.4.2.58-universal.jar                   | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe     | 2.4.2.58                    | ForgeMultipart-1.12.2-2.4.2.58-universal.jar                   | None                                     |
	| UCHIJAAAA | ironchest                 | 1.12.2-7.0.44.829           | ironchest-1.12.2-7.0.44.829.jar                                | None                                     |
	| UCHIJAAAA | luckperms                 | 4.2.25                      | LuckPerms-Sponge-4.2.25.jar                                    | None                                     |
	| UCHIJAAAA | mrtjpcore                 | 2.1.3.35                    | MrTJPCore-1.12.2-2.1.3.35-universal.jar                        | None                                     |
	| UCHIJAAAA | projectred-core           | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-Base.jar                            | None                                     |
	| UCHIJAAAA | projectred-integration    | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-integration.jar                     | None                                     |
	| UCHIJAAAA | projectred-transmission   | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-integration.jar                     | None                                     |
	| UCHIJAAAA | projectred-illumination   | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-lighting.jar                        | None                                     |
	| UCHIJAAAA | projectred-expansion      | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-mechanical.jar                      | None                                     |
	| UCHIJAAAA | projectred-transportation | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-mechanical.jar                      | None                                     |
	| UCHIJAAAA | projectred-exploration    | 4.8.6.74                    | ProjectRed-1.12.2-4.8.6.74-world.jar                           | None                                     |
	| UCHIJAAAA | thaumcraft                | 6.1.BETA16                  | Thaumcraft-1.12.2-6.1.BETA16.jar                               | None                                     |
	| UCHIJAAAA | thermalexpansion          | 5.5.0                       | ThermalExpansion-1.12.2-5.5.0.29-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics           | 2.5.1                       | ThermalDynamics-1.12.2-2.5.1.14-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | worldborder               | 1.0.0                       | World-Border-1.12.2-1.0.5.jar                                  | None                                     |
	| UCHIJAAAA | immersiveengineering      | 0.12-82                     | ImmersiveEngineering-0.12-82.jar                               | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b155.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3242.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 8 / 50; ]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)`

**Comment by F9Alejandro** [comment]
It has to do with the Air Material and the focus pouch
