### ISSUE TITLE
Null Pointer Exception Preventing Startup

### ISSUE THREAD

**Issue by operatoroperon** [Azanor/thaumcraft-beta#1092]
Hi! I reported another Null Pointer Exception in issue #532, and haven't been able to start the mod. I updated to the most recent build (Beta 17) and got this error. I have no idea if the two are identical, or related, but this is preventing me from so much as loading the game with Thaumcraft installed and I would appreciate it if you'd look into it. A full crash report is below, and #532 contains the previous crash report.

Thanks! 
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/2/18 7:51 PM
Description: Initializing game

java.lang.NoClassDefFoundError: scala/NotImplementedError
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_51_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:128)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_51_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 251460752 bytes (239 MB) / 814219264 bytes (776 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                           | Signature                                |
	|:----- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCH   | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.3.2655.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge      | 14.23.3.2655 | forge-1.12.2-14.23.3.2655.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCH   | thaumcraft | 6.1.BETA17   | Thaumcraft-1.12.2-6.1.BETA17.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

**Comment by Riyshn** [comment]
Crash report appears to be different, but also getting a NullPointerException crash on server load after updating to B17.

https://pastebin.com/SbB6uZj2

**Comment by wamc2017** [comment]
@operatoroperon,

looks like you're missing the scala libraries, try reinstalling your minecraft/forge instance, or use multimc/twitch client or something like this for a test...

@Riyshn,

you crash is completely different and should be fixed, if you update Thaumic Additions to the latest version...

**Comment by Riyshn** [comment]
...yup, that did it. I suppose that's what I get for trusting the Twitch client for updates instead of checking manually.

**Comment by operatoroperon** [comment]
@wamc2017 I updated Forge to the latest version, but it's still giving me the error. Is there anywhere I can get these libraries manually? The Forge universal installer said it acquired them, but I don't know where it would put them, or how to check if they installed correctly if so.

**Comment by wamc2017** [comment]
Hmm, under libraries/org/scala-lang in your instance folder there should be several folders with the libraries included, don't know where to get them...

But have you tried multimc or the twitch client? Those come preconfigured and download everything you need to play modded...

**Comment by Azanor** [comment]
Has this been resolved yet or is there something I need to look at?
