### ISSUE TITLE
Fatal crash on connect: drawTagsOnContainer(...)

### ISSUE THREAD

**Issue by dragonpaw** [Azanor/thaumcraft-beta#1116]
One of my users is no longer able to log in. Every time she connects to my server, she disconnects with this crash:

```
java.lang.NullPointerException: Unexpected error
	at thaumcraft.client.lib.events.RenderEventHandler.drawTagsOnContainer(RenderEventHandler.java:832)
	at thaumcraft.client.lib.events.RenderEventHandler.blockHighlight(RenderEventHandler.java:487)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_45_RenderEventHandler_blockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```
Full gist: https://gist.github.com/dragonpaw/eaae5acb671006387f09aeaaae1cbfe6

**Comment by F9Alejandro** [comment]
Try updating Thaumic JEI to 1.4.0 and see if that may be contributing to the issue, also try out Beta 17 too.

**Comment by Azanor** [comment]
Did that solve your issues?

**Comment by dragonpaw** [comment]
Unfortunately we can't test the fix, as we're running ATM3 on the server. I'll point them at this bug to see if they want to uptake the fixes. 

In the end, I was able to teleport her away from the TC equipment while she was logging in, and then after that she could log in successfully. So it's definitely something to do with the initial loading of the world while in view of the blocks. (And after finally making it so she could log in, she broke the blocks and didn't go back to using the mod.)
