### ISSUE TITLE
API error thrown

### ISSUE THREAD

**Issue by tyggna** [Azanor/thaumcraft-beta#1118]
This is a super-low priority bug, I'm just going through my server logs and reporting all errors.
Basically the "Hats" mod can't add hats to thaumcraft mobs because of an API call error, could be on their end, not sure, so submitting bugs to both packs.

Server version is forge-1.12.2-14.23.4.2705
Thaumcraft is 1.12.2-6.1.BETA17
Hats is 1.12.2-7.0.2

> [17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ExceptionInInitializerError
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName0(Native Method)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at java.lang.Class.forName(Class.java:264)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:         at me.ichun.mods.hats.common.thread.ThreadGetModMobSupport.run(ThreadGetModMobSupport.java:49)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.NullPointerException
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.api.ThaumcraftApiHelper.makeCrystal(ThaumcraftApiHelper.java:362)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.api.ThaumcraftApiHelper.makeCrystal(ThaumcraftApiHelper.java:372)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         at thaumcraft.common.entities.monster.EntityPech.<clinit>(EntityPech.java:830)
[17:09:10] [Hats Mod Mob Support Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]:         ... 3 more

**Comment by Azanor** [comment]
Oh wow, finally log errors that explains that bug that has been around for ages!
