### ISSUE TITLE
Map corrupted after breaking a Flux Condenser Lattice

### ISSUE THREAD

**Issue by Ultrices** [Azanor/thaumcraft-beta#1172]
I was playing Thaumcraft 6 Beta 17 for days and recently tried to use the Flux Condenser. When the lattices got clogged, I've tried to break 'em — _'cause I didn't know what happened at first_ — and the game crashed.

The game is still crashing every time I try to enter the map, even disabling all the other mods.

Here's the _resume_ of my last crash report: — _Idk if it is enougth_

> Description: Ticking block entity java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at thaumcraft.common.tiles.devices.TileCondenser.func_73660_a(TileCondenser.java:57)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by wamc2017** [comment]
Dupe of #1095 
Try setting Remove Erroring Entities to true in the forge cfg to recover your world or use mcedit...

**Comment by Ultrices** [comment]
Sorry, I didn't found this article.

It worked, thank you!
