### ISSUE TITLE
Client crash!

### ISSUE THREAD

**Issue by prokopiy** [Azanor/thaumcraft-beta#1206]
[17:03:33] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1487) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:321) [1AZLauncher.jar:?]
	at launcher.lOlkEKchebureK.main(SourceFile:204) [1AZLauncher.jar:?]
Caused by: java.lang.NullPointerException
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$6(ColorHandler.java:142) ~[ColorHandler.class:?]
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148) ~[bin.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:499) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:541) ~[bzw.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217) ~[CCRenderItem.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265) ~[bmg.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98) ~[bmg.class:?]
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:32) ~[bmm.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at Reflector.callVoid(Reflector.java:636) ~[Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457) ~[buq.class:?]
	... 11 more
[17:03:34] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.9.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 7/26/18 5:03 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$6(ColorHandler.java:142)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:499)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:541)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:32)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:321)
	at launcher.lOlkEKchebureK.main(SourceFile:204)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$6(ColorHandler.java:142)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:499)

-- Item being rendered --
Details:
	Item Type: thaumcraft.common.items.resources.ItemCrystalEssence@44a37c5b
	Item Aux: 0
	Item NBT: {Aspects:[{amount:1,key:"Tinctura"}]}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:541)

-- Item being rendered --
Details:
	Item Type: thaumcraft.common.items.resources.ItemCrystalEssence@44a37c5b
	Item Aux: 0
	Item NBT: {Aspects:[{amount:1,key:"Tinctura"}]}
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:217)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.gui.inventory.GuiChest.func_73863_a(SourceFile:32)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:636)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiChest
	Mouse location: Scaled: (306, 182). Absolute: (613, 365)
	Screen size: Scaled: (613, 365). Absolute: (1226, 730). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['uncom'/49654, l='MpServer', x=71.64, y=72.00, z=-3.56]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (70,73,-4), Chunk: (at 6,4,12 in 4,-1; contains blocks 64,0,-16 to 79,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 23447053 game time, 2731726 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 6 total; [EntityCow['Корова'/69, l='MpServer', x=117.55, y=67.00, z=42.55], EntityCow['Корова'/57, l='MpServer', x=32.16, y=66.00, z=30.24], EntityCow['Корова'/58, l='MpServer', x=37.14, y=66.00, z=37.26], GCEntityClientPlayerMP['uncom'/49654, l='MpServer', x=71.64, y=72.00, z=-3.56], EntityVillager['Крестьянин'/60, l='MpServer', x=57.30, y=69.00, z=19.30], EntityCow['Корова'/63, l='MpServer', x=76.51, y=68.00, z=-45.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:321)
	at launcher.lOlkEKchebureK.main(SourceFile:204)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-29-generic
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1518876064 bytes (1448 MB) / 3207856128 bytes (3059 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072M -Xmx3072M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+DisableAttachMechanism
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_D1 99 mods loaded, 99 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by prokopiy** [comment]
Previous in inventory.

Use Thaumcraft-1.12.2-6.1.BETA19.jar

Also crash in world:

[17:39:56] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:458) ~[bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393) ~[bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:823) ~[buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1791) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614) ~[buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385) ~[buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12-launcherfixed.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12-launcherfixed.jar:?]
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:321) [1AZLauncher.jar:?]
	at launcher.lOlkEKchebureK.main(SourceFile:204) [1AZLauncher.jar:?]
Caused by: java.lang.NullPointerException
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$7(ColorHandler.java:155) ~[ColorHandler.class:?]
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148) ~[bin.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134) ~[bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199) ~[bzw.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:92) ~[CCRenderItem.class:?]
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:138) ~[bzu.class:?]
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19) ~[bzu.class:?]
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:33) ~[WrappedEntityItemRenderer.class:?]
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:16) ~[WrappedEntityItemRenderer.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416) ~[bzf.class:?]
	... 16 more
[17:39:57] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.9.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  CorePlugin (SmoothFont-1.12.2-1.15.jar)
  DLFMLCorePlugin (DynamicLights-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 7/26/18 5:39 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$7(ColorHandler.java:155)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:92)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:138)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:33)
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:16)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:823)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1791)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at launcher.lOlkEKchebureK.LoLkeKChEbUREk(SourceFile:321)
	at launcher.lOlkEKchebureK.main(SourceFile:204)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$7(ColorHandler.java:155)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:148)
	at net.minecraft.client.renderer.RenderItem.func_191970_a(RenderItem.java:339)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:162)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:134)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:199)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:92)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:138)
	at net.minecraft.client.renderer.entity.RenderEntityItem.func_76986_a(RenderEntityItem.java:19)
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:33)
	at codechicken.lib.render.item.entity.WrappedEntityItemRenderer.func_76986_a(WrappedEntityItemRenderer.java:16)

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 6662
	Entity Name: item.tile.jar_normal
	Entity's Exact location: -2377.25, 81.00, -1834.66
	Entity's Block location: World: (-2378,81,-1835), Chunk: (at 6,5,5 in -149,-115; contains blocks -2384,0,-1840 to -2369,255,-1825), Region: (-5,-4; contains chunks -160,-128 to -129,-97, blocks -2560,0,-2048 to -2049,255,-1537)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: codechicken.lib.render.item.entity.WrappedEntityItemRenderer@23068209
	Location: -4.75,0.31,-2.16 - World: (-5,0,-3), Chunk: (at 11,0,13 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -57.65625
	Delta: 0.35992432
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:416)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:393)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:823)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1791)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)

**Comment by prokopiy** [comment]
tried it without optifine, crashed also...

[18:58:57] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world

....

-- Entity being rendered --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.EntityItem)
	Entity ID: 106237
	Entity Name: item.tile.jar_normal
	Entity's Exact location: -2377.25, 81.00, -1834.67
	Entity's Block location: World: (-2378,81,-1835), Chunk: (at 6,5,5 in -149,-115; contains blocks -2384,0,-1840 to -2369,255,-1825), Region: (-5,-4; contains chunks -160,-128 to -129,-97, blocks -2560,0,-2048 to -2049,255,-1537)
	Entity's Momentum: 0.00, -0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: codechicken.lib.render.item.entity.WrappedEntityItemRenderer@3084d58
	Location: -4.75,0.00,-2.17 - World: (-5,0,-3), Chunk: (at 11,0,13 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -57.65625
	Delta: 0.6000862
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)

**Comment by wamc2017** [comment]
Please use [pastebin](https://pastebin.com) or [gist](https://gist.github.com) in the future to post your crash reports.
Do you got other mods installed? Maybe some other mod which adds aspects crashes Thaumcraft rendering (in the first report there's the aspect Tinctura mentioned, I haven't seen this in any mod yet, do you know which mod adds it?)

**Comment by prokopiy** [comment]
Planar Artifice

**Comment by prokopiy** [comment]
But what is this error?:
https://paste.dimdev.org/haqitiwiqe.mccrash

**Comment by wamc2017** [comment]
Does it happen without vanillafix or micdoodle core/galacticraft?
