### ISSUE TITLE
ClassNotFoundException at thaumcraft.common.config.ConfigRecipes.initializeNormalRecipes(ConfigRecipes.java:1282)

### ISSUE THREAD

**Issue by wjrogers** [Azanor/thaumcraft-beta#1235]
Logged by FML as "Error building events" during startup. This appears to be a new error in Thaumcraft-1.12.2-6.1.BETA20:
```
[12:34:30] [main/ERROR] [FML]: Error building events.
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraft.item.ItemStack
	at org.objectweb.asm.ClassWriter.getCommonSuperClass(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassWriter.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.Frame.a(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.MethodNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.tree.ClassNode.accept(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:85) [forge-1.12.2-14.23.4.2739.jar:?]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) [ASMTransformerWrapper$TransformerWrapper.class:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(Unknown Source) [?:1.8.0_181]
	at thaumcraft.common.config.ConfigRecipes.initializeNormalRecipes(ConfigRecipes.java:1282) [ConfigRecipes.class:?]
	at thaumcraft.Registrar.registerVanillaRecipes(Registrar.java:87) [Registrar.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_63_Registrar_registerVanillaRecipes_Register.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762) [GameData.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by wjrogers** [comment]
Here's a complete log. Forge version 14.23.4.2739.
[2018-08-03-2.log.gz](https://github.com/Azanor/thaumcraft-beta/files/2258201/2018-08-03-2.log.gz)

**Comment by Hubry** [comment]
Probably the same thing as Azanor/thaumcraft-api#38 (please keep open as Azanor doesnt seem to look at that tracker at all).

**Comment by cpw** [comment]
Not probably. That is the error. See my issue for an explanation.
