### ISSUE TITLE
Beta 21 Crash on start up

### ISSUE THREAD

**Issue by TnSLucas** [Azanor/thaumcraft-beta#1283]
I've tried different forge and thaumcraft versions, help me out, seems like something to do with a crystal 

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/11/18 1:18 AM
Description: Initializing game

java.lang.NoClassDefFoundError: scala/NotImplementedError
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:386)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_171, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 66168080 bytes (63 MB) / 281284608 bytes (268 MB) up to 7481327616 bytes (7134 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx7G -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2729 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                               | Signature                                |
	|:----- |:---------- |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                        | None                                     |
	| UCH   | mcp        | 9.42         | minecraft.jar                        | None                                     |
	| UCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.4.2729.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge      | 14.23.4.2729 | forge-1.12.2-14.23.4.2729.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar               | None                                     |
	| UCH   | thaumcraft | 6.1.BETA21   | Thaumcraft-1.12.2-6.1.BETA21 (1).jar | None                                     |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2729
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7560D GL version 4.2.12422 Compatibility Profile Context 13.152.1.1000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default+Improved+PBR+1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-5500 APU with Radeon(tm) HD Graphics

**Comment by F9Alejandro** [comment]
please use gist or hastebin for crash logs.
