### ISSUE TITLE
Game Crash when loading game

### ISSUE THREAD

**Issue by Ribbons0121R121** [Azanor/thaumcraft-beta#1475]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 10/5/18 9:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class thaumcraft.common.lib.crafting.ThaumcraftCraftingManager
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getPotionReagentsRecursive(ThaumcraftCraftingManager.java:337)
	at thaumcraft.common.config.ConfigAspects.getPotionAspects(ConfigAspects.java:692)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:525)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:36)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:82)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:54)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 526388944 bytes (502 MB) / 916979712 bytes (874 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version       | Source                                  | Signature                                |
	|:------ |:------------- |:------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft     | 1.12.2        | minecraft.jar                           | None                                     |
	| UCHIJ  | mcp           | 9.42          | minecraft.jar                           | None                                     |
	| UCHIJ  | FML           | 8.0.99.99     | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge         | 14.23.5.2768  | forge-1.12.2-14.23.5.2768-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | orbis_api     | 1.12.2-1.1.91 | orbis_api-1.12.2-1.1.91.jar             | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJ  | aether        | 1.12.2-1.1.0  | aether_ii-1.12.2-1.1.0.jar              | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| UCHIJ  | aether_legacy | 1.12.2-v3.2   | aether_legacy-1.12.2-v3.2.jar           | None                                     |
	| UCHIJ  | baubles       | 1.5.2         | Baubles-1.12-1.5.2.jar                  | None                                     |
	| UCHIJ  | colytra       | 1.1.0         | colytra-1.12.2-1.1.0.jar                | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJ  | tammodized    | 0.15.5        | TamModized-1.12.1-0.15.5.jar            | None                                     |
	| UCHIEE | thaumcraft    | 6.1.BETA25    | Thaumcraft-1.12.2-6.1.BETA25.jar        | None                                     |
	| UCHI   | voidcraft     | 0.26.10       | VoidCraft-1.12-0.26.10.jar              | None                                     |

	Loaded coremods (and transformers): 
ColytraLoadingPlugin (colytra-1.12.2-1.1.0.jar)
  c4.colytra.asm.ElytraTransformer
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.25.19' Renderer: 'Intel(R) HD Graphics 6000'

**Comment by kuroyure** [comment]
same here, happened when i updated forge

**Comment by Ioandar** [comment]
New AE2 needs at least 2768
Thaumcraft crashes using 2768

So downgrade AE2 to previous version and set Forge to 2766, yes?

**Comment by P3rf3ctXZer0** [comment]
@loandar "So downgrade AE2 to previous version and set Forge to 2766, yes?"

yeah no - at any rate let me know when this mod is stable.
