### ISSUE TITLE
Thaumatorium throws NPE when ticked

### ISSUE THREAD

**Issue by Zekrom64** [Azanor/thaumcraft-beta#1513]
Our server has started having an issue where a Thaumatorium with a hopper attached to it will throw a NullPointerException when ticked. We're running the Enigmatica 2 Expert modpack v1.41 with Thaumcraft 6.1 beta 26.

Important part:
`net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at thaumcraft.common.tiles.crafting.TileThaumatoriumTop.func_191420_l(TileThaumatoriumTop.java:262) ~[TileThaumatoriumTop.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_174916_c(TileEntityHopper.java:457) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122) ~[avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more`

Full crash report:
[crash-2018-10-19_23.48.09-server.txt](https://github.com/Azanor/thaumcraft-beta/files/2497779/crash-2018-10-19_23.48.09-server.txt)

**Comment by Xobra** [comment]
What was your setup? Where did you put the Hopper?

**Comment by Zekrom64** [comment]
The thaumatorium had a hopper feeding from a chest into the top, and was ejecting into a hopper storing the output into a chest.

**Comment by Xobra** [comment]
Like this?

![test](https://user-images.githubusercontent.com/42319576/47260287-f5efbb00-d4b8-11e8-969f-fc2d6c7b9a55.png)

It didn't crash in this case

**Comment by wamc2017** [comment]
Try disabling Faster Hopper in the foamfix.cfg (this may not fix your current world, because the entity is already ticking, so you may also need to enable removeErroringEntities in forge.cfg)

**Comment by Quantum001** [comment]
Zekrom and I administrate this server. This is a screenshot of the Thaumatorium's configuration.
![2018-10-20_20 36 11](https://user-images.githubusercontent.com/25472638/47262223-17947680-d4a8-11e8-82d3-45f1c643688c.png)

**Comment by lOmicronl** [comment]
I have also seen something like this happen in a singleplayer, superflat test world with Beta 25.

Unfortunately, since it was a test world containing nothing of value, and I couldn't get to load it at all, I simply deleted it. The crash log talked about hoppers, so I thought it might be a vanilla issue, and didn't report it here. The only hoppers in that world were on top of thaumatoriums, though, so it replicated this setup.

**Comment by Jkosio23** [comment]
I get the same issue on world load in singleplayer with beta 25, but it doesn't crash if I put the hopper back on after world loading. I do not have foamfix, but I do have diet hoppers.
