### ISSUE TITLE
cant interact with arcane pedestal

### ISSUE THREAD

**Issue by SpeedrunnerG55** [Azanor/thaumcraft-beta#1519]
after you place the arcane pedestal you can't use it.
and every time you look at it this constantly comes up on the server console, and in single player it crashes the client

mods list

`AbyssalCraft-1.12.2-1.9.4.13.jar
AbyssalCraft+Integration-1.12.2-1.6.6.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AkashicTome-1.2-10.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv6-stable-2.jar
astralsorcery-1.12.2-1.9.4.jar
AutoRegLib-1.3-20.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BloodMagic-1.12.2-2.3.3-101.jar
Botania+r1.10-356.jar
CarryOn+MC1.12.2+v1.11.1.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-0.2.1.35.jar
chiselsandbits-14.26.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.1.22-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
compactmachines3-1.12.2-3.0.12-b215.jar
ComputerCraft1.80pr1.jar
conarm-1.12.2-1.2.0.jar
CTM-MC1.12.2-0.3.2.18.jar
Cucumber-1.12.2-1.1.1.jar
EnderCore-1.12.2-0.5.41.jar
EnderIO-1.12.2-5.0.36.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
environmentaltech-1.12.2-2.0.17.1.jar
ExpandedEquivalence-1.12.2-11b.jar
ExtraCells-1.12.2-2.6.1a.jar
extrautils2-1.12-1.9.6.jar
ExtremeReactors-1.12.2-0.4.5.49.jar
FastLeafDecay-v14.jar
flatcoloredblocks-mc1.12-6.6.jar
Forgelin-1.7.4.jar
ForgeMultipart-1.12.2-2.6.0.79-universal.jar
Guide-API-1.12-2.1.6-61.jar
HammerCore-1.12.2-2.0.3.1.jar
Hats-1.12.2-7.0.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.1.4.jar
ImmersiveEngineering-0.12-86.jar
immersivepetroleum-1.12.2-1.1.9.jar
industrialcraft-2-2.8.73-ex112.jar
industrialforegoing-1.12.2-1.11.5-215.jar
InventoryTweaks-1.63.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.40.824.jar
jei_1.12.2-4.12.1.217.jar
LuckPerms-Sponge-4.3.11.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
Mantle-1.12-1.3.2.24.jar
Mekanism-1.12.2-9.4.13.349.jar
MekanismGenerators-1.12.2-9.4.13.349.jar
MekanismTools-1.12.2-9.4.13.349.jar
moartinkers-0.6.0.jar
MobGrindingUtils-0.3.11.jar
monk-mod-1.4.jar
Morpheus-1.12-3.3.2.jar
MouseTweaks-2.8-mc1.12.1.jar
MrTJPCore-1.12.2-2.1.3.35-universal.jar
MysticalAgriculture-1.12-1.6.13.jar
NuclearCraft-2.12e--1.12.2.jar
Nucleus-1.6.2-S7.1-MC1.12.2-plugin.jar
OpenBlocks-1.12.2-1.8.jar
OpenModsLib-1.12.2-0.12.1.jar
orbis_api-1.12.2-1.1.91.jar
p455w0rdslib-1.12-2.0.35.jar
ProjectE-1.12-PE1.3.0.jar
ProjectRed-1.12.2-4.9.1.92-Base.jar
ProjectRed-1.12.2-4.9.1.92-compat.jar
ProjectRed-1.12.2-4.9.1.92-fabrication.jar
ProjectRed-1.12.2-4.9.1.92-integration.jar
ProjectRed-1.12.2-4.9.1.92-lighting.jar
ProjectRed-1.12.2-4.9.1.92-mechanical.jar
ProjectRed-1.12.2-4.9.1.92-world.jar
quantumflux-1.12.2-2.0.16.jar
RandomThings-MC1.12.2-4.2.2.jar
reauth-3.6.0.jar
RedstoneArsenal-1.12.2-2.6.1.15-universal.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
Snad-1.12.1-1.7.09.16a.jar
_spongeforge-1.12.2-2705-7.1.0-BETA-3361.jar
StorageDrawers-1.12.2-5.3.7.jar
TConstruct-1.12.2-2.10.1.87.jar
tesla-core-lib-1.12.2-1.0.15.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
Thaumic_Gadgets_1.12.2_0.1.4.5_tb.24.jar
ThaumicJEI-1.12.2-1.5.4-22.jar
thaumictinkerer-1.12.2-5.0-353c71c.jar
TheBetweenlands-3.3.13-universal.jar
ThermalCultivation-1.12.2-0.3.1.8-universal.jar
ThermalDynamics-1.12.2-2.5.3.16-universal.jar
ThermalExpansion-1.12.2-5.5.2.39-universal.jar
ThermalFoundation-1.12.2-2.6.1.22-universal.jar
ThermalInnovation-1.12.2-0.3.1.8-universal.jar
TinkerToolLeveling-1.12.2-1.0.5.jar
twilightforest-1.12.2-3.8.689-universal.jar
valkyrielib-1.12.2-2.0.17.3.jar
Wawla-1.12.2-2.5.264.jar
Waystones_1.12.2-4.0.67.jar
WirelessCraftingTerminal-1.12.2-3.9.68.jar
worldedit-forge-mc1.12-6.1.8-dist.jar
zerocore-1.12-0.1.2.2.jar`

```
[14:01:58] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task                         
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Part
icle                                                                                                       
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_181]                      
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_181]                         
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]                                
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:293) [SpongeImplHook
s.class:1.12.2-2705-7.1.0-BETA-3361]                                                                       
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3963) [Minecraft
Server.class:?]                                                                                            
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.cla
ss:?]                                                                                                      
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:
?]                                                                                                         
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.cla
ss:?]                                                                                                      
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]    
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]                                             
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle                          
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_181]                          
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_181]                  
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_181]                                 
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_181]                                      
        at thaumcraft.common.blocks.BlockTCTile.func_149915_a(BlockTCTile.java:41) ~[BlockTCTile.class:?]  
        at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]                      
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]                    
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]                    
        at net.minecraft.world.World.func_175625_s(World.java:6356) ~[amu.class:?]                         
        at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:6
9) ~[MessageRequestTile$Handler.class:?]                                                                   
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrap
per-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_181]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_181]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_181]
        at thaumcraft.common.blocks.BlockTCTile.func_149915_a(BlockTCTile.java:41) ~[BlockTCTile.class:?]
        at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:6356) ~[amu.class:?]
        at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:6
9) ~[MessageRequestTile$Handler.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```

**Comment by Torradera** [comment]
Got a similar error on my server only running Thaumcraft. When I put the Arcane Pedestal on the floor or break it, the server crashes. After reseting, the pedestal stay on the floor and in my hand. If I attempt to put again or break, it sometimes crashes again. Confusing, but i think there's a bug. 

```
---- Minecraft Crash Report ----
// Oops.

Time: 23/10/18 02:04
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at thaumcraft.common.blocks.BlockTCTile.func_149915_a(BlockTCTile.java:41)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at thaumcraft.common.blocks.BlockTCTile.func_149915_a(BlockTCTile.java:41)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800)
	at net.minecraft.world.World.func_175625_s(World.java:2399)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['Torradera'/385, l='world', x=-319,80, y=68,00, z=66,34], EntityPlayerMP['goblin verde'/1804, l='world', x=-49,36, y=89,86, z=-56,75]]
	Chunk stats: ServerChunkCache: 890 Drop: 0
	Level seed: 2655771794118128694
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-132,64,84), Chunk: (at 12,4,4 in -9,5; contains blocks -144,0,80 to -129,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3431621 game time, 1981040 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 16328 (now: false), thunder time: 2500 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1518663080 bytes (1448 MB) / 1974992896 bytes (1883 MB) up to 1974992896 bytes (1883 MB)
	JVM Flags: 2 total; -Xmx2G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                                  | Signature                                |
	|:--------- |:---------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2772-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.5.2772 | forge-1.12.2-14.23.5.2772-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar                  | None                                     |
	| UCHIJAAAA | thaumcraft | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar        | None                                     |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 2 / 8; [EntityPlayerMP['Torradera'/385, l='world', x=-319,80, y=68,00, z=66,34], EntityPlayerMP['goblin verde'/1804, l='world', x=-49,36, y=89,86, z=-56,75]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Azanor** [comment]
This has been hotfixed. Redownload b26 to fix this issue.
