### ISSUE TITLE
invalid vis crystal crash

### ISSUE THREAD

**Issue by captcookie** [Azanor/thaumcraft-beta#1523]
https://paste.dimdev.org/acanebofaj.mccrash

Time: 2018-10-22 19:21:57 CDT
Description: Updating screen events

java.lang.NullPointerException
    at thaumcraft.common.container.slot.SlotCrystal.isValidCrystal(SlotCrystal.java:29)
    at thaumcraft.common.container.slot.SlotCrystal.isItemValid(SlotCrystal.java:23)
    at net.minecraft.inventory.Container.slotClick(Container.java:306)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseReleased(GuiContainer.java:604)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:543)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1758)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Beta 26

I simply made a phial and it made an excess vis shard that looked like ordo shard. It had a long item tag and when i tried to remove it from the table, i was perma kicked from logging in.

**Comment by captcookie** [comment]
[https://cdn.discordapp.com/attachments/237339636568031232/504090417315315712/ScreenHunter_1844_Oct._22_19.33.jpg](url)

[https://cdn.discordapp.com/attachments/237339636568031232/504090437229740033/ScreenHunter_1845_Oct._22_19.34.jpg](url)

**Comment by wamc2017** [comment]
Hmm, does this happen without CombinedPotions installed?

**Comment by Azanor** [comment]
I would like to know that myself.

**Comment by captcookie** [comment]
When i rerolled the server and removed combined potions. i tested and the crystal does not appear. I believe combined potions was a mod conflict. thanks for the help.
