### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by Gysburi** [Azanor/thaumcraft-beta#1543]
[15:09:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:09:23] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2772 for Minecraft 1.12.2 loading
[15:09:23] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_181
[15:09:23] [main/INFO] [FML]: Searching C:\Users\PLAYER\AppData\Roaming\.minecraft\mods for mods
[15:09:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:09:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:09:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[15:09:25] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[15:09:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:09:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:09:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:09:25] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[15:09:25] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[15:09:26] [main/INFO] [minecraft/Minecraft]: Setting user: PLAYER
[15:09:29] [main/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[15:09:30] [main/INFO] [FML]: -- System Details --
Details:
 Minecraft Version: 1.12.2
 Operating System: Windows 7 (amd64) version 6.1
 Java Version: 1.8.0_181, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 124819832 bytes (119 MB) / 254488576 bytes (242 MB) up to 2134114304 bytes (2035 MB)
 JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: 
 Loaded coremods (and transformers): 
 GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
[15:09:30] [main/INFO] [FML]: MinecraftForge v14.23.5.2772 Initialized
[15:09:30] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[15:09:30] [main/INFO] [FML]: Replaced 1036 ore ingredients
[15:09:31] [main/INFO] [FML]: Searching C:\Users\PLAYER\AppData\Roaming\.minecraft\mods for mods
[15:09:32] [main/INFO] [FML]: Forge Mod Loader has identified 6 mods to load
[15:09:32] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, baubles, thaumcraft] at CLIENT
[15:09:32] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, baubles, thaumcraft] at SERVER
[15:09:33] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 100310336 nanos
[15:09:33] [main/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Baubles, FMLFileResourcePack:Thaumcraft
[15:09:33] [main/INFO] [FML]: Processing ObjectHolder annotations
[15:09:33] [main/INFO] [FML]: Found 1170 ObjectHolder annotations
[15:09:33] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[15:09:33] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[15:09:33] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[15:09:33] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[15:09:33] [main/INFO] [FML]: OBJLoader: Domain thaumcraft has been added.
[15:09:33] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: AHEAD Target: null
[15:09:34] [main/INFO] [FML]: Applying holder lookups
[15:09:34] [main/INFO] [FML]: Holder lookups applied
[15:09:34] [main/INFO] [FML]: Applying holder lookups
[15:09:34] [main/INFO] [FML]: Holder lookups applied
[15:09:34] [main/INFO] [FML]: Applying holder lookups
[15:09:34] [main/INFO] [FML]: Holder lookups applied
[15:09:34] [main/INFO] [FML]: Applying holder lookups
[15:09:34] [main/INFO] [FML]: Holder lookups applied
[15:09:34] [main/INFO] [FML]: Injecting itemstacks
[15:09:34] [main/INFO] [FML]: Itemstack injection complete
[15:09:35] [main/WARN] [minecraft/SoundManager]: Missing sound for event: thaumcraft:runicshieldcharge
[15:09:35] [Sound Library Loader/INFO] [minecraft/SoundManager]: Starting up SoundSystem...
[15:09:36] [Thread-5/INFO] [minecraft/SoundManager]: Initializing LWJGL OpenAL
[15:09:36] [Thread-5/INFO] [minecraft/SoundManager]: (The LWJGL binding of OpenAL. For more information, see http://www.lwjgl.org)
[15:09:36] [Thread-5/INFO] [minecraft/SoundManager]: OpenAL initialized.
[15:09:36] [Sound Library Loader/INFO] [minecraft/SoundManager]: Sound engine started
[15:09:38] [main/INFO] [FML]: OBJLoader.MaterialLibrary: key '' (model: 'thaumcraft:models/block/arcane_workbench_charger.mtl') is not currently supported, skipping
[15:09:38] [main/INFO] [FML]: OBJLoader.MaterialLibrary: key '' (model: 'thaumcraft:models/block/pillar.mtl') is not currently supported, skipping
[15:09:38] [main/INFO] [FML]: OBJLoader.MaterialLibrary: key '' (model: 'thaumcraft:models/block/thaumatorium.mtl') is not currently supported, skipping
[15:09:39] [main/INFO] [FML]: OBJLoader.MaterialLibrary: key '' (model: 'thaumcraft:models/block/golembuilder.mtl') is not currently supported, skipping
[15:09:39] [main/INFO] [FML]: OBJLoader.MaterialLibrary: key '' (model: 'thaumcraft:models/item/scanner.mtl') is not currently supported, skipping
[15:09:39] [main/INFO] [FML]: Max texture size: 16384
[15:09:42] [main/INFO] [minecraft/TextureMap]: Created: 1024x512 textures-atlas
[15:09:43] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.ModelBakeEvent@7af66767:
java.lang.NoClassDefFoundError: scala/NotImplementedError
 at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38) ~[CrystalModel.class:?]
 at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141) ~[ProxyBlock$BakeBlockEventHandler.class:?]
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic) ~[?:?]
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
 at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
 at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:399) [ForgeHooksClient.class:?]
 at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30) [cgc.class:?]
 at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) [bib.class:?]
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
 at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_181]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_181]
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
 ... 17 more
Caused by: java.lang.NullPointerException
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
 ... 17 more
[15:09:43] [main/ERROR] [FML]: Index: 1 Listeners:
[15:09:43] [main/ERROR] [FML]: 0: NORMAL
[15:09:43] [main/ERROR] [FML]: 1: ASM: class thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler onModelBakeEvent(Lnet/minecraftforge/client/event/ModelBakeEvent;)V
[15:09:43] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/3/18 3:09 PM
Description: Initializing game

java.lang.NoClassDefFoundError: scala/NotImplementedError
 at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
 at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
 at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
 at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:399)
 at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
 at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 ... 17 more
Caused by: java.lang.NullPointerException
 at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
 ... 19 more

 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
 at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
 at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
 at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
 at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
 at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:399)
 at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
 at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
 at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
 at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
 at net.minecraft.client.main.Main.main(SourceFile:123)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
 at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
 Minecraft Version: 1.12.2
 Operating System: Windows 7 (amd64) version 6.1
 Java Version: 1.8.0_181, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
 Memory: 107087488 bytes (102 MB) / 374771712 bytes (357 MB) up to 2134114304 bytes (2035 MB)
 JVM Flags: 6 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP 9.42 Powered by Forge 14.23.5.2772 6 mods loaded, 6 mods active
 States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
 |:----- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
 | UCH | minecraft | 1.12.2 | minecraft.jar | None |
 | UCH | mcp | 9.42 | minecraft.jar | None |
 | UCH | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2772.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
 | UCH | forge | 14.23.5.2772 | forge-1.12.2-14.23.5.2772.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
 | UCH | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None |
 | UCH | thaumcraft | 6.1.BETA26 | Thaumcraft-1.12.2-6.1.BETA26.jar | None |

Loaded coremods (and transformers): 
 GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
 Launched Version: 1.12.2-forge1.12.2-14.23.5.2772
 LWJGL: 2.9.4
 OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.34, NVIDIA Corporation
 GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: No
 Is Modded: Definitely; Client brand changed to 'fml,forge'
 Type: Client (map_client.txt)
 Resource Packs: 
 Current Language: English (US)
 Profiler Position: N/A (disabled)
 CPU: 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
[15:09:43] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\PLAYER\AppData\Roaming\.minecraft\crash-reports\crash-2018-11-03_15.09.43-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by wamc2017** [comment]
Hmm, looks like https://github.com/Azanor/thaumcraft-beta/issues/1092

Try reinstalling forge, seems like your installation are missing the scala binarys, you could also give MultiMC or the Twitch Client a try...

**Comment by Gysburi** [comment]
Thx!
But it still weird, i tried a pack with 21 mods it worked perfectly... just thaumcraft didn't work. Now magically, without reinstallation it works...
