### ISSUE TITLE
Research table client log-spam and drop

### ISSUE THREAD

**Issue by Orygeunik** [Azanor/thaumcraft-beta#1568]
**Describe the bug**
If you click the right mouse button on the table for research, in the logs of the client begins to be written multiple error (below). It is also possible to drop client

**Additional context**
![default](https://user-images.githubusercontent.com/6960655/48986563-f585b800-f127-11e8-8bab-32d4d8019472.png)

> [02:05:51] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:224) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[MessageToMessageEncoder.class:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:?]
	at thaumcraft.common.tiles.TileThaumcraft.sendMessageToClient(TileThaumcraft.java:33) [TileThaumcraft.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncSlots(TileThaumcraftInventory.java:134) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.func_70299_a(TileThaumcraftInventory.java:91) [TileThaumcraftInventory.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) [agr.class:?]
	at net.minecraft.inventory.Container.func_75141_a(Container.java:519) [afr.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1154) [brz.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:30) [iu.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:10) [iu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_192]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_192]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_192]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_192]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Environment

- MP
- jre1.8.0_181 (Upgrade to 191 in queue)
- Mods (excluding dependencies):

- buildcraft-7.99.19
- buildcraft-compat-7.99.15
- forestry_1.12.2-5.8.2.374
- industrialcraft-2-2.8.104-ex112
- jei_1.12.2-4.13.1.225
- ProjectRed-1.12.2-4.9.1.92
- UniDict-1.12.2-2.9.1
- TConstruct-1.12.2-2.11.0.106
- Thaumcraft-1.12.2-6.1.BETA26
- practicallogistics2-1.12.2-3.0.5-8
- ironchest-1.12.2-7.0.52.838

---
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-4
- Forge Version: 1.12.2 - 14.23.5.2784

**Comment by rinart73** [comment]
Happens to me too. Makes it impossible to use this mod in MP.
Version: 6.1.BETA26

**Comment by Celmas** [comment]
Same. Did Somebody fix it?

**Comment by raymondbh** [comment]
I have the same after getting quite far into the mod. It is a pity that Azanor stops this beautiful mod.... :/
