### ISSUE TITLE
Insta crash after changing dimension

### ISSUE THREAD

**Issue by Thepawer** [Azanor/thaumcraft-beta#1588]
I got this crash after going from the nether to the overworld. My world is really heavy since I have farms of everything that can be farmeable. After I got this crash, everytime I try to open up the world I get an insta crash. I checked the world with MCedit and everything seems to be fine, no chunks corrupted. Would appreciate any kind of help, since I would not like to lose a world that took me too many hours. (I had F3 + G on when this happened)

Crash log:
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 12/18/18 3:22 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at thaumcraft.common.tiles.crafting.TileThaumatoriumTop.func_191420_l(TileThaumatoriumTop.java:262)
	at net.minecraft.tileentity.TileEntityHopper.func_174916_c(TileEntityHopper.java:457)
	at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.tiles.crafting.TileThaumatoriumTop.func_191420_l(TileThaumatoriumTop.java:262)
	at net.minecraft.tileentity.TileEntityHopper.func_174916_c(TileEntityHopper.java:457)
	at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper // minecraft:hopper)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (195,81,-177), Chunk: (at 3,5,15 in 12,-12; contains blocks 192,0,-192 to 207,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper // minecraft:hopper)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Thaumcraft 6
	All players: 1 total; [EntityPlayerMP['Thepawer'/265, l='Thaumcraft 6', x=70.19, y=86.85, z=-256.97]]
	Chunk stats: ServerChunkCache: 1227 Drop: 0
	Level seed: 8607478726809458543
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (136,64,252), Chunk: (at 8,4,12 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 29261602 game time, 33796991 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 37262 (now: false), thunder time: 44738 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 165137048 bytes (157 MB) / 704643072 bytes (672 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.5.2772 | forge-1.12.2-14.23.5.2772.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCHIJAAAA | thaumcraft | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Thepawer'/265, l='Thaumcraft 6', x=70.19, y=86.85, z=-256.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Thepawer** [comment]
Fixed it thanks to this issue https://github.com/Azanor/thaumcraft-beta/issues/1513
