### ISSUE TITLE
Minecraft 1.12.2 thaumcraft crash when i trying start a game

### ISSUE THREAD

**Issue by erugen123123123123** [Azanor/thaumcraft-beta#1594]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/23/18 4:58 PM
Description: Initializing game

java.lang.NoClassDefFoundError: scala/NotImplementedError
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:399)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: scala.NotImplementedError
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 17 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.client.renderers.block.CrystalModel.<init>(CrystalModel.java:38)
	at thaumcraft.proxies.ProxyBlock$BakeBlockEventHandler.onModelBakeEvent(ProxyBlock.java:141)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_BakeBlockEventHandler_onModelBakeEvent_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:399)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 69969864 bytes (66 MB) / 326893568 bytes (311 MB) up to 5277745152 bytes (5033 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx5045M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2760 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID         | Version      | Source                           | Signature                                |
	|:----- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCH   | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCH   | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCH   | FML        | 8.0.99.99    | forge-1.12.2-14.23.4.2760.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge      | 14.23.4.2760 | forge-1.12.2-14.23.4.2760.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | baubles    | 1.5.2        | Baubles-Mod-1.12.2.jar           | None                                     |
	| UCH   | thaumcraft | 6.1.BETA25   | Thaumcraft-1.12.2-6.1.BETA25.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 23.20.16.5018' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2760
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.5018, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz\

trying on ver.2796,2768,2766,2767,2764 and 2760

**Comment by 256leon** [comment]
Quote from the Changelog:

> 6.1.BETA26
> [...]
> - fix for crash related to the latest versions of forge (14.23.5.2768)
> 

and

https://github.com/Azanor/thaumcraft-beta/issues/1504#issuecomment-430578370

i hope it is a help for you

**Comment by Gunner76th** [comment]
[Crash_report_doc.txt](https://github.com/Azanor/thaumcraft-beta/files/5908817/Crash_report_doc.txt)
Just had a user present this crash to us for Roguelike Adventures and Dungeons. 6.1 Beta 26 is still kicking the same crash.

**Comment by Gunner76th** [comment]
[crash-2021-02-02_15.16.23-client.txt](https://github.com/Azanor/thaumcraft-beta/files/5911847/crash-2021-02-02_15.16.23-client.txt)
[latest (23).log](https://github.com/Azanor/thaumcraft-beta/files/5911849/latest.23.log)

2 more log files regarding this crash and the Scala error that was supposed to have already been fixed.
