### ISSUE TITLE
[B26] Ticking Block entity NullPointerException with the Thaumatorium

### ISSUE THREAD

**Issue by praecipitator** [Azanor/thaumcraft-beta#1611]
```
[19:44:29] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at thaumcraft.common.tiles.crafting.TileThaumatoriumTop.func_191420_l(TileThaumatoriumTop.java:262) ~[TileThaumatoriumTop.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_174916_c(TileEntityHopper.java:457) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137) ~[avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122) ~[avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
```
Unfortunately I can't give more info. The server can't even start.

Edit: it worked fine for quite a while. The thaumatorium had a hopper attached to it from above, and had one mnemonic matrix

**Comment by praecipitator** [comment]
Some other infos which might be relevant:

The thaumatorium had also an emptying essentia transfuser attached to the back of it's top. The mnemonic matrix was attached to the right side of the top.

It's output was facing into a vanilla chest standing on one of those stone tables (not infusion pedestals, one of the things you need for the golem press)

I can't remember what it was crafting when it broke. But the last things I made were sanity soap and liquid death. Those might have still been saved in the matrix. When I broke the hopper after MCEditing the thaumatorium out, I got some empty buckets and blocks of flesh.

**Comment by fightmesun** [comment]
Literally had the same situation happen to me though the thaumatorium was crafting something else. Hopper attached to the top and one mneomic matrix on the side. I had the hopper filled with quartz shards so I can turn excess esstentias into crystals.
