### ISSUE TITLE
Smoking a Great Wood Pipe causes server disconnect

### ISSUE THREAD

**Issue by kreezxil** [Azanor/thaumcraft-beta#1629]
In version 6.1.BETA26
A player of mine in my pack World of Dragons reported that while having the Great Wood pipe plus the tobacco pile in their inventory, when they go to smoke it, each time they are disconnected from the server.

In single player it works fine.

What the console says:
```
[11:13:00] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /64.31.193.174:53947
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_189651_aD()Lnet/minecraft/util/math/Vec3d;
        at com.rumaruka.tb.common.item.ItemSmokingPipe.onUsingTick(ItemSmokingPipe.java:103) ~[ItemSmokingPipe.class:?]
        at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2097) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more
```

**Comment by androshalforc** [comment]
i dont think this is a TC issue while greatwood trees are added in thaumcraft there are no pipes or tobacco. this sounds like an incompatability from an other mod

ps ATM thaumcraft is no longer in development however there has been some talk of it being continued by another dev

**Comment by kreezxil** [comment]
are you sure about the pipe, the modid for the pipes say "thaumcraft:"

**Comment by androshalforc** [comment]
I am 99 percent sure

I have never seen a smoking pipe/ tobacco in the mod i can double check when i get home 

I would check what mod adds the tobacco it probably added the other pipes as well and checked and created pipes for all kinds of wood available since thaumcraft adds silverwood and greatwood they got added by the pipe mod but credited it to thaumcraft for some reason. 

Im no coder however so take that with a grain of salt

**Comment by Serifina** [comment]
1. When reporting a crash, _always_ include the full crashlog, not just a snippet.
2. Smoking pipes are from Thaumic Bases, _not_ Thaumcraft, making this crash mis-reported anyway. Go report it [there](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/issues).

**Comment by kreezxil** [comment]
In regards to your 1) there was no crash on either side, simply smoking the pipe causes a player to disconnect from the server, therefore that snippet is highly relevant.

Also thank you for point out that it was Thaumic Bases, silly me for trusting my player, i should've double checked it myself.
