### ISSUE TITLE
Crash with thaumcraft No enum constant

### ISSUE THREAD

**Issue by KCiMbo** [Azanor/thaumcraft-beta#1633]
I have this error with thaumcraft 4 and actually all mods that add biomes, I have no clue where to ask for help anymore. I posted this on mostly all forums but no response yet. Please help me Iam really out of ideas.

Here is the crash-report.
https://pastebin.com/c1KcKD8x

```
[INFO] Adding biome mapping 192 Tainted Land at BiomeBase[192]

[WARNING] java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.Tainted Land

[WARNING] at java.lang.Enum.valueOf(Enum.java:238)

[WARNING] at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.initMappings(CraftBlock.java:578)

[WARNING] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:337)

[WARNING] at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462)

[WARNING] at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:137)

[WARNING] at net.minecraft.world.World.<init>(World.java:349)

[WARNING] at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)

[WARNING] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)

[WARNING] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:335)

[WARNING] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)

[WARNING] at java.lang.Thread.run(Thread.java:813)

[WARNING] Forge Mod Loader detected that the backup level.dat is being used.```

**Comment by mahtaran** [comment]
Did you find a fix for this issue yet? I am encountering the same issue.

**Comment by KCiMbo** [comment]
No I did not fix it yet, Iam still searching for a fix. However noone seems to have it.
