### ISSUE TITLE
Research Table lags

### ISSUE THREAD

**Issue by Lulz322** [Azanor/thaumcraft-beta#1649]
Guys, need ur help.
I just created a server in minecraft 1.12.2, and found one trouble: When someone open research table everyone player on server lags on few seconds, and when someone scrolling pages happens the same.
Has anyone encountered such a problem?

**Comment by CmdrJane** [comment]
Same happens to my server

Console log: 
`[21:05:46] [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.network.FMLOutboundHandler$OutboundTarget$7.selectNetworks(FMLOutboundHandler.java:224) ~[FMLOutboundHandler$OutboundTarget$7.class:?]
	at net.minecraftforge.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:378) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToAllAround(SimpleNetworkWrapper.java:264) [SimpleNetworkWrapper.class:?]
	at thaumcraft.common.tiles.TileThaumcraft.sendMessageToClient(TileThaumcraft.java:33) [TileThaumcraft.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncSlots(TileThaumcraftInventory.java:134) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.TileThaumcraftInventory.syncTile(TileThaumcraftInventory.java:141) [TileThaumcraftInventory.class:?]
	at thaumcraft.common.tiles.crafting.TileResearchTable.onDataPacket(TileResearchTable.java:182) [TileResearchTable.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1231) [brz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:54) [ih.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) [ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by ghost** [comment]
check my serv 88.9.181.105:25565

**Comment by ThatScar** [comment]
Same problem here.
What's weird is this: it only happens for my friends and not me. It seems we all have the same setup but exactly 2 of us don't experience this issue and everyone else does.
Still experimenting...

**Comment by raizsl** [comment]
> Same problem here.
> What's weird is this: it only happens for my friends and not me. It seems we all have the same setup but exactly 2 of us don't experience this issue and everyone else does.
> Still experimenting...

I have this problem too, i have lags, but my friend doesn't

**Comment by ThatScar** [comment]
Alright, I have instructed all of my friends to **reset the config folders** to the modpack default and, for some reason, that did the trick. No idea why they weren't the same in the first place. Something is still off but I think this remedied the problem enough that the game is playable and we no longer care about it.
EDIT: a surefire way to do what I did is to just zip the config folder from a player who doesn't have this issue and send it to everyone else. It is still unknown which config files actually matter so I wouldn't be sure what to send here, we were playing a custom modpack I've made.

**Comment by Ismartrooper81** [comment]
I have the same problem. At first, everytime we enter the server, all works fine. But after using the research table a few times it starts to become laggy, and a few more uses later the game crashes and we have to restart the game.

**Comment by Shirlineyn** [comment]
Removing tc6aspects4jei worked for me
https://board.aternos.org/thread/29702-1-12-2-thaumcraft-6-is-laggy/?postID=110894#post110894

**Comment by Lulz322** [comment]
> 
> 
> Alright, I have instructed all of my friends to **reset the config folders** to the modpack default and, for some reason, that did the trick. No idea why they weren't the same in the first place. Something is still off but I think this remedied the problem enough that the game is playable and we no longer care about it.
> EDIT: a surefire way to do what I did is to just zip the config folder from a player who doesn't have this issue and send it to everyone else. It is still unknown which config files actually matter so I wouldn't be sure what to send here, we were playing a custom modpack I've made.

yo, can u send ur config folder, probably it can fix.

**Comment by BabyMagnum99** [comment]
Could you help me so well?

**Comment by Lulz322** [comment]
> 
> 
> Could you help me so well?

What happend?

**Comment by dimka511** [comment]
I got rid of lags by removing the BetterFps mod

**Comment by Lulz322** [comment]
I fixed it by install original Forge Version, w/out any other Launchers, using only official versions of Minecraft Launcher and Forge
