### ISSUE TITLE
Thaumcraft Potentially Crashing Server - Related to Magical Forest

### ISSUE THREAD

**Issue by AwesomeAnimationGamer** [Azanor/thaumcraft-beta#1728]
[Running Thaumcraft Beta 26]
For a while now on my server, I have been getting semi-frequent crashes that look like this:
```
java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:691)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:223)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
I have attached the full crash log below. Since this error lists no culprit mods and is instead citing Minecraft itself, I had no way to troubleshoot it. Until recently, that is, when it happened 3 times in a row while I was traversing a Magical Forest. This prompted me to do some more testing, and it consistently happened while a Magical Forest was loaded (I was lucky to go 20 seconds without the server crashing). Once I played for a few hours away from any Magical Forest with no crashes whatsoever, I asked around and a lot of people on the server who had experienced the crash confirmed that they were in or near a Magical Forest when the server went down. 
The above crash has been going on for a few weeks now intermittently, but something else strange is going on now. Last night one of my players reported that the server was lagging really badly. When I checked the server console, I noticed that Thaumcraft is suddenly stopping and starting its aura thread every 15 seconds, causing immense amounts of lag that has started crashing the server by causing it to run out of memory:
```
1:33:23 PM [INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@42aea9d)
1:33:23 PM [INFO] [THAUMCRAFT]: Creating aura cache for world -1
1:33:24 PM [Thread-29/INFO] [THAUMCRAFT]: Stopping aura thread for dim -1
1:33:24 PM [Thread-30/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
1:33:35 PM [INFO] [THAUMCRAFT]: Removing aura cache for world -1
1:33:35 PM [INFO] [FML]: Unloading dimension -1
1:33:36 PM [INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@42aea9d)
1:33:36 PM [INFO] [THAUMCRAFT]: Creating aura cache for world -1
1:33:36 PM [Thread-30/INFO] [THAUMCRAFT]: Stopping aura thread for dim -1
1:33:36 PM [Thread-31/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
1:33:50 PM [INFO] [THAUMCRAFT]: Removing aura cache for world -1
1:33:50 PM [INFO] [FML]: Unloading dimension -1
1:33:50 PM [INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@42aea9d)
1:33:50 PM [INFO] [THAUMCRAFT]: Creating aura cache for world -1
1:33:51 PM [Thread-31/INFO] [THAUMCRAFT]: Stopping aura thread for dim -1
1:33:51 PM [Thread-32/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
```
I don't want to outright remove Thaumcraft, since multiple players on the server have made significant progress with it already. Any help is greatly appreciated. Thank you for your time.
[crash-2019-10-22_16.42.50-server.txt](https://github.com/Azanor/thaumcraft-beta/files/3763745/crash-2019-10-22_16.42.50-server.txt)

**Comment by Jaderey** [comment]
I too was also very confused at what was causing this until i stumbled across your post. Fortunately a way to disable the generation of Magical Forest Biome within the Thuamcraft config itself.

A second thing Azanor has abandoned this mod and any mod he may have been working on for personal reasons stating he even stated he was done modding Minecraft somewhere. In any-case anything wrong with thuamcraft is likely to be left that way unless he returns.

**Comment by wamc2017** [comment]
Hmm, I think I've seen the "TickNextTick list out of synch" error on several issue trackers a while ago. Looks like this is a bug in Java itself, there's a mod called [RandomPatches](https://www.curseforge.com/minecraft/mc-mods/randompatches) which includes a "TickNextTick list out of synch" fix, which helped me to solve that problem...
