### ISSUE TITLE
I need help with my modpack.

### ISSUE THREAD

**Issue by SenpaiStrawz** [Azanor/thaumcraft-beta#1774]
I just want to play on my modpack but i just keeps saying this

The game crashed whilst initializing game
Error: java.lang.NullPointerException: Initializing game
Exit Code: -1

Idk what it means.
Here's the crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 10/28/20 5:07 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at electroblob.wizardry.client.model.BakedModelGenerateOverrides.bake(BakedModelGenerateOverrides.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_439_BakedModelGenerateOverrides_bake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at electroblob.wizardry.client.model.BakedModelGenerateOverrides.bake(BakedModelGenerateOverrides.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_439_BakedModelGenerateOverrides_bake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:414)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 702454392 bytes (669 MB) / 2270167040 bytes (2165 MB) up to 5011144704 bytes (4779 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5376m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                         | Signature                                |
	|:----- |:--------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2                   | minecraft.jar                                  | None                                     |
	| LCH   | mcp                   | 9.42                     | minecraft.jar                                  | None                                     |
	| LCH   | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCH   | thaumcraft            | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
	| LCH   | botania               | r1.10-363                | Botania r1.10-363.jar                          | None                                     |
	| LCH   | aiotbotania           | 0.7.1                    | aiotbotania-0.7.1.jar                          | None                                     |
	| LCH   | alcatrazcore          | 1.0.4                    | alcatrazcore-1.0.4.jar                         | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | autoreglib            | 1.3-32                   | AutoRegLib-1.3-32.jar                          | None                                     |
	| LCH   | biomesoplenty         | 7.0.1.2441               | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar  | None                                     |
	| LCH   | guideapi              | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                    | None                                     |
	| LCH   | bloodmagic            | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                | None                                     |
	| LCH   | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bookworm              | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                    | None                                     |
	| LCH   | castle_dungeons       | 1.3                      | castle_dungeons-1.3-1.12.2.jar                 | None                                     |
	| LCH   | cat                   | 0.1                      | CavesAndDungeonsMod.jar                        | None                                     |
	| LCH   | cosmeticarmorreworked | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | crafttweaker          | 4.1.20                   | CraftTweaker2-1.12-4.1.20.586.jar              | None                                     |
	| LCH   | ctgui                 | 1.0.0                    | CraftTweaker2-1.12-4.1.20.586.jar              | None                                     |
	| LCH   | crafttweakerjei       | 2.0.3                    | CraftTweaker2-1.12-4.1.20.586.jar              | None                                     |
	| LCH   | customizeddungeonloot | 1.0.3                    | Customized-Dungeon-Loot-1.12 -(v.1.0.3).jar    | None                                     |
	| LCH   | dmonsters             | 1.7                      | Deadly Monsters 1.71.jar                       | None                                     |
	| LCH   | gottschcore           | 1.13.1                   | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar | None                                     |
	| LCH   | dungeons2             | 1.7.5                    | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.5.jar    | None                                     |
	| LCH   | dungeonsmod           | 1.12.2-1.0.5             | DungeonsMod-1.12.2-1.0.5.jar                   | None                                     |
	| LCH   | dynamictrees          | 1.12.2-0.9.19            | DynamicTrees-1.12.2-0.9.19.jar                 | None                                     |
	| LCH   | dynamictreesbop       | 1.12.2-1.4.4             | DynamicTreesBOP-1.12.2-1.4.4.jar               | None                                     |
	| LCH   | dynamictreestc        | 1.12.2-1.4.2             | DynamicTreesTC-1.12.2-1.4.2.jar                | None                                     |
	| LCH   | ebwizardry            | 4.3                      | ElectroblobsWizardry-4.3-MC1.12.2.jar          | None                                     |
	| LCH   | embers                | 0.230                    | embers-0.230.jar                               | None                                     |
	| LCH   | ironchest             | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCH   | jetorches             | 2.1.0                    | jetorches-1.12.2-2.1.0.jar                     | None                                     |
	| LCH   | journeymap            | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                    | None                                     |
	| LCH   | jrftl                 | 1.1                      | JRFTL[1.12.2]-1.1.jar                          | None                                     |
	| LCH   | jaff                  | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                  | None                                     |
	| LCH   | jeresources           | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar        | None                                     |
	| LCH   | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCH   | mcwbridges            | 1.0.4                    | mcw-bridges-1.0.4-mc1.12.2.jar                 | None                                     |
	| LCH   | msmlegacy             | @VERSION@                | MoreSwordsLegacy-1.12.2-1.0.7.jar              | None                                     |
	| LCH   | nether_dungeon        | 1.0.1                    | nether_dungeon-1.0.1.jar                       | None                                     |
	| LCH   | notreepunching        | 2.0.21                   | notreepunching-2.0.21.jar                      | None                                     |
	| LCH   | potioncore            | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                  | None                                     |
	| LCH   | qualitytools          | 1.0.7_for_1.12.2         | QualityTools-1.0.7_for_1.12.2.jar              | None                                     |
	| LCH   | t3s4ebw               | 1.0                      | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar   | None                                     |
	| LCH   | soundfilters          | 0.12.1_for_1.12          | SoundFilters-0.12.1_for_1.12.jar               | None                                     |
	| LCH   | spartanweaponry       | beta 1.3.8               | SpartanWeaponry-1.12.2-beta-1.3.8.jar          | None                                     |
	| LCH   | spartancompat         | @VERSION@                | spartancompat-1.2.3.jar                        | None                                     |
	| LCH   | spartanshields        | 1.5.4                    | SpartanShields-1.12.2-1.5.4.jar                | None                                     |
	| LCH   | spartanweaponryarcana | beta 1.0.3               | SpartanWeaponryArcana-1.12.2-beta-1.0.3.jar    | None                                     |
	| LCH   | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCH   | tfa                   | 1.1                      | TFA_1.1.jar                                    | None                                     |
	| LCH   | thaumicjei            | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                 | None                                     |
	| LCH   | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar            | None                                     |
	| LCH   | toughasnails          | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar    | None                                     |
	| LCH   | xat                   | 0.30                     | Trinkets and Baubles-0.30.1.jar                | None                                     |
	| LCH   | zawa                  | 1.12.2-2.1.0             | zawa-1.12.2-2.1.0.jar                          | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
	| LCH   | betteranimalsplus     | 9.0.1                    | betteranimalsplus-1.12.2-9.0.1.jar             | None                                     |
	| LCH   | orelib                | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7325' Renderer: 'Intel(R) HD Graphics 520'
	No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.6.0 - Build 26.20.100.7325, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7325
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4

Thank you in advance.

**Comment by Serifina** [comment]
Please take the time to actually read the crash report. The error is with Electroblob's Wizardry, not Thaumcraft. You should contact the author of that mod for help.

**Comment by SenpaiStrawz** [comment]
ok thx
