### ISSUE TITLE
Server crash caused by arcane bore

### ISSUE THREAD

**Issue by zzzhly** [Azanor/thaumcraft-beta#1791]
I am experiencing a server crash problem after I have activated my arcane bore, here is the crash report.
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/18/21 4:51 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:98)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:902)
	at net.minecraft.server.dedicated.DedicatedServer.func_175579_a(DedicatedServer.java:534)
	at net.minecraft.world.WorldServer.canMineBlockBody(WorldServer.java:857)
	at net.minecraft.world.WorldProvider.canMineBlock(WorldProvider.java:543)
	at net.minecraft.world.World.func_175660_a(World.java:3559)
	at net.minecraft.world.WorldServer.func_175660_a(WorldServer.java:853)
	at net.tslat.aoa3.event.PlayerEvents.onBlockBreak(PlayerEvents.java:340)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_PlayerEvents_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851)
	at thaumcraft.common.lib.utils.BlockUtils.harvestBlock(BlockUtils.java:88)
	at thaumcraft.common.entities.construct.EntityArcaneBore.dig(EntityArcaneBore.java:295)
	at thaumcraft.common.entities.construct.EntityArcaneBore.func_70071_h_(EntityArcaneBore.java:158)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2016)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.world.World.func_72866_a(World.java:1991)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72866_a(World.java:2056)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:98)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:902)
	at net.minecraft.server.dedicated.DedicatedServer.func_175579_a(DedicatedServer.java:534)
	at net.minecraft.world.WorldServer.canMineBlockBody(WorldServer.java:857)
	at net.minecraft.world.WorldProvider.canMineBlock(WorldProvider.java:543)
	at net.minecraft.world.World.func_175660_a(World.java:3559)
	at net.minecraft.world.WorldServer.func_175660_a(WorldServer.java:853)
	at net.tslat.aoa3.event.PlayerEvents.onBlockBreak(PlayerEvents.java:340)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_PlayerEvents_onBlockBreak_BreakEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:851)
	at thaumcraft.common.lib.utils.BlockUtils.harvestBlock(BlockUtils.java:88)
	at thaumcraft.common.entities.construct.EntityArcaneBore.dig(EntityArcaneBore.java:295)
	at thaumcraft.common.entities.construct.EntityArcaneBore.func_70071_h_(EntityArcaneBore.java:158)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2016)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
	at net.minecraft.world.World.func_72866_a(World.java:1991)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72866_a(World.java:2056)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecraft:minecart (net.minecraft.entity.item.EntityMinecartEmpty)
	Entity ID: 1664881
	Entity Name: entity.MinecartRideable.name
	Entity's Exact location: -173.50, 11.06, -68.47
	Entity's Block location: World: (-174,11,-69), Chunk: (at 2,0,11 in -11,-5; contains blocks -176,0,-80 to -161,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.00, 0.44
	Entity's Passengers: [EntityArcaneBore['Arcane Bore'/1665571, l='world', x=-173.50, y=11.06, z=-68.75]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['long_xer'/1611936, l='world', x=-172.62, y=11.88, z=-64.57]]
	Chunk stats: ServerChunkCache: 697 Drop: 0
	Level seed: 2669447019016881051
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-48,64,256), Chunk: (at 0,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 26794714 game time, 15485529 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 74957 (now: false), thunder time: 76396 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-154-generic
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1887988000 bytes (1800 MB) / 8353742848 bytes (7966 MB) up to 8353742848 bytes (7966 MB)
	JVM Flags: 5 total; -Xms8000M -Xmx8000M -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                              | Version                  | Source                                        | Signature                                |
	|:------ |:------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                       | 1.12.2                   | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                             | 9.42                     | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                           | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | foamfixcore                     | 7.7.4                    | minecraft.jar                                 | None                                     |
	| LCHIJA | tweakersconstruct               | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar            | None                                     |
	| LCHIJA | aoa3                            | 3.3.6                    | AoA3-3.3.6.jar                                | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | jei                             | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LCHIJA | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | twilightforest                  | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar | None                                     |
	| LCHIJA | tconstruct                      | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | conarm                          | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                    | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | armoryexpansion                 | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHIJA | armoryexpansion-custommaterials | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHIJA | armoryexpansion-iceandfire      | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHIJA | armoryexpansion-matteroverdrive | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHIJA | foamfix                         | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                    | None                                     |
	| LCHIJA | ftblib                          | 5.4.7.2                  | FTBLib-5.4.7.2.jar                            | None                                     |
	| LCHIJA | forgeessentials                 | 12.3                     | forgeessentials-1.12.2-12.3.82-server.jar     | None                                     |
	| LCHIJA | ftbutilities                    | 5.4.1.130                | FTBUtilities-5.4.1.130.jar                    | None                                     |
	| LCHIJA | itemfilters                     | 1.0.4.2                  | ItemFilters-1.0.4.2.jar                       | None                                     |
	| LCHIJA | ftbquests                       | 1202.9.0.13              | FTBQuests-1202.9.0.13.jar                     | None                                     |
	| LCHIJA | ftbbackups                      | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.5.jar               | None                                     |
	| LCHIJA | ironchest                       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | mm_lib                          | 2.3.0                    | MMLib-2.3.0.jar                               | None                                     |
	| LCHIJA | patchouli                       | 1.0-21                   | Patchouli-1.0-21.jar                          | None                                     |
	| LCHIJA | plustic                         | @VERSION@                | plustic-8.0.3.jar                             | None                                     |
	| LCHIJA | sakura                          | 1.0.7-1.12.2             | Sakura-1.0.7-1.12.2.jar                       | None                                     |
	| LCHIJA | flammpfeil.slashblade           | mc1.12-r33               | SlashBlade-mc1.12-r33.jar                     | None                                     |
	| LCHIJA | slashblade_addon                | 1.6.0                    | SJAP-1.6.0.jar                                | None                                     |
	| LCHIJA | slashbladetic                   | 1.5.0-MC1.12.2           | SlashBladeTic-1.5.0-MC1.12.2.jar              | None                                     |
	| LCHIJA | tinkertoolleveling              | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar           | None                                     |
	| LCHIJA | touhou_little_maid              | 1.2.4                    | touhoulittlemaid-1.12.2-1.2.4-release.jar     | None                                     |
	| LCHIJA | travelersbackpack               | 1.0.35                   | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LCHIJA | armoryexpansion-conarm          | 1.4.2                    | armoryexpansion-1.4.2.jar                     | None                                     |
	| LCHIJA | tweakersconstructpostload       | 1.12.2-1.6.1             | tweakersconstruct-1.12.2-1.6.1.jar            | None                                     |

	Loaded coremods (and transformers): 
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	ForgeEssentials: Running ForgeEssentials 12.3.82 (b9cf068). Modules loaded: Chat, Commands, Economy, JScripting, Multiworld, Permissions, PlayerLogger, Protection, Remote, SignTools, Teleport, Tickets, WorldBorder
	Profiler Position: N/A (disabled)
	Player Count: 1 / 50; [EntityPlayerMP['long_xer'/1611936, l='world', x=-172.62, y=11.88, z=-64.57]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Gatvik** [comment]
Hi, do u found the solution? I have same problem(
