### ISSUE TITLE
Beta3 Crash

### ISSUE THREAD

**Issue by Focalist** [Azanor/thaumcraft-beta#203]
Using forge 2511 wish just Beta3 and baubles 1.3.13.
Every time I try to open my inventory the game crashes. Can't find the error message at the moment, but it did specify the inventory and baubles.

Here Error: java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_147003_i from class baubles.client.gui.GuiEvents

**Comment by EPIICTHUNDERCAT** [comment]
Find the crash report in your crash reports folder. are you using twitch app?

**Comment by Focalist** [comment]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/1/18 8:01 PM
Description: Unexpected error

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.inventory.GuiContainer.field_147003_i from class baubles.client.gui.GuiEvents
	at baubles.client.gui.GuiEvents.guiPostInit(GuiEvents.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_GuiEvents_guiPostInit_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:497)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2110)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at baubles.client.gui.GuiEvents.guiPostInit(GuiEvents.java:22)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_GuiEvents_guiPostInit_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:497)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2110)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Focalist'/352, l='MpServer', x=168.33, y=70.00, z=246.58]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (168,64,256), Chunk: (at 8,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 540 game time, 540 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 16 total; [EntityZombie['Zombie'/224, l='MpServer', x=165.50, y=21.00, z=217.50], EntityZombie['Zombie'/227, l='MpServer', x=174.34, y=45.00, z=217.44], EntityZombie['Zombie'/261, l='MpServer', x=187.73, y=34.00, z=217.52], EntityCreeper['Creeper'/262, l='MpServer', x=177.50, y=45.00, z=218.50], EntityZombie['Zombie'/264, l='MpServer', x=180.57, y=14.14, z=223.50], EntityBat['Bat'/233, l='MpServer', x=176.37, y=16.84, z=225.58], EntitySkeleton['Skeleton'/265, l='MpServer', x=182.50, y=35.00, z=245.50], EntityBat['Bat'/234, l='MpServer', x=177.22, y=16.00, z=225.46], EntityItem['item.tile.dirt.default'/235, l='MpServer', x=167.59, y=69.00, z=247.88], EntityPlayerSP['Focalist'/352, l='MpServer', x=168.33, y=70.00, z=246.58], EntitySheep['Sheep'/184, l='MpServer', x=148.50, y=66.00, z=217.50], EntitySheep['Sheep'/185, l='MpServer', x=151.50, y=64.00, z=216.50], EntityBat['Bat'/186, l='MpServer', x=139.70, y=26.00, z=238.55], EntityBat['Bat'/187, l='MpServer', x=149.05, y=28.95, z=240.97], EntitySheep['Sheep'/188, l='MpServer', x=151.50, y=65.00, z=225.55], EntityCreeper['Creeper'/189, l='MpServer', x=147.50, y=27.00, z=240.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 332442920 bytes (317 MB) / 956301312 bytes (912 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.zip) 
	UCHIJAAAA	thaumcraft{6.0.BETA3} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA3.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2511
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by EndermanLOTR** [comment]
Looks like the bug from **Baubles** not _Thaumcraft._

**Comment by raphydaphy** [comment]
but baubles is also by azanor and a requirement for TC

**Comment by LucyDopey** [comment]
I've been having the same problem but with a later beta

**Comment by EPIICTHUNDERCAT** [comment]
haha, this is due to some ASM lol, i wouldnt know how to fix it anyways ;-;
