### ISSUE TITLE
Mod Conflic

### ISSUE THREAD

**Issue by cvcvz1** [Azanor/thaumcraft-beta#226]
I never talked about bugs for any mods before but the most recent public beta for thaumcraft 6 isn't compatible with Mo'Creatures for 1.10.2. Everything works except for the ability to set golems down. Though you might want to know

**Comment by Azanor** [comment]
Could you give a bit more details please?

**Comment by cvcvz1** [comment]
I don't know anything about the coding. But Mo'Creatures and Custom Mob
spawner prevent you from setting the golem down. You can set seals down and
make them in a press but when you right click them to place them in the
world they won't spawn. I'll try and play with the config of Mo'Creatures
but something in the spawning of the custom mobs seems to be blocking golem
from spawning when you set them in the world.

**Comment by DeliciousTea** [comment]
I was actually just doing some pretty extensive testing with various mods to figure out what was going on with this issue. It's definitely something to do with Mo Creatures itself, nothing to do with Custom Mob Spawner. Seems to be an entity ID conflict which is something I've never seen before, personally. Here's the error for ya Azanor: 

`[12:15:59] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Duplicate id value for 16!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 16!
	at net.minecraft.network.datasync.EntityDataManager.func_187214_a(SourceFile:79) ~[kk.class:?]
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70088_a(EntityThaumcraftGolem.java:97) ~[EntityThaumcraftGolem.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:203) ~[rw.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:155) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) ~[sg.class:?]
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:18) ~[sm.class:?]
	at thaumcraft.common.entities.construct.EntityOwnedConstruct.<init>(EntityOwnedConstruct.java:34) ~[EntityOwnedConstruct.class:?]
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.<init>(EntityThaumcraftGolem.java:70) ~[EntityThaumcraftGolem.class:?]
	at thaumcraft.common.entities.construct.golem.ItemGolemPlacer.onItemUseFirst(ItemGolemPlacer.java:102) ~[ItemGolemPlacer.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:439) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more`

Thanks for all your work!
