### ISSUE TITLE
Thaumcraft 6 Beta 4 Crashing while scrolling through JEI

### ISSUE THREAD

**Issue by Creator256** [Azanor/thaumcraft-beta#248]
I am not sure what is causing this issue, but I have put Thaumcraft into a custom modpack I am playing, and every time I scroll to a page in JEI that has what appears to be Focuses from thaumcraft, the game crashes. It produces both a server and a client crash log. I have narrowed it down to thaumcraft by removing all other mods and it still appears to happen. 

The client error is the following: 
```
Time: 2/9/18 1:18 PM
Description: Rendering ingredient

java.lang.NullPointerException: Rendering ingredient
	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$11(ColorHandler.java:183)
	at thaumcraft.client.ColorHandler$$Lambda$1555/110780488.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:125)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:97)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1600_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

And the server error crash is the following:
```
Time: 2/9/18 1:18 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at codechicken.wirelessredstone.handler.WREventHandler.serverTick(WREventHandler.java:150)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1044_WREventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

It is strange to me that both a client and server error are appearing at the same time when the game crashes.

**Comment by MatthiasMann** [comment]
I have the same crashes.
[crash-2018-02-09_23.50.03-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1712669/crash-2018-02-09_23.50.03-client.txt)
[crash-2018-02-09_23.50.03-server.txt](https://github.com/Azanor/thaumcraft-beta/files/1712670/crash-2018-02-09_23.50.03-server.txt)

**Comment by Duke-Archibald** [comment]
me too not the most anoying bug but can be frustating 

this is the minecraft game output classed as a fatal error

`Reported exception thrown!
net.minecraft.util.ReportedException: Rendering ingredient
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at thaumcraft.common.items.casters.ItemFocus.getFocusColors(ItemFocus.java:42)
	at thaumcraft.client.ColorHandler.lambda$registerItemColourHandlers$11(ColorHandler.java:183)
	at thaumcraft.client.ColorHandler$$Lambda$212/223461531.func_186726_a(Unknown Source)
	at net.minecraft.client.renderer.color.ItemColors.func_186728_a(ItemColors.java:139)
	at net.minecraft.client.renderer.RenderItem.func_175032_a(RenderItem.java:217)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:125)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:97)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:164)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_638_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	... 9 more`
and the crash log 
[crash-2018-02-09_22.26.36-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1712973/crash-2018-02-09_22.26.36-client.txt)
