### ISSUE TITLE
[Beta 4] Cannot make the research table

### ISSUE THREAD

**Issue by rgz0** [Azanor/thaumcraft-beta#259]
Hi, 

I am having an issue when I try to create the research table. I have the scribing tools and the wood table. I place the wood table and I am trying to put the scribing tools on it, but it does not work. I am using more mods with a pack I made on the twitch app. Can it be some other mod that is making this?

This is the export of my profile, if it helps.
[Omnius Pack 1.10-1.0.zip]()

**Comment by rgz0** [comment]
Sorry about creating an issue without digging too much into it myself. I am not deleting the ticket because it may be it is of your interest as well. It looks like some other mod changes the way the player interacts with objects, which causes the behaviour I described before. I noticed that in the logs of my server (which I am posting with this). Could someone help me figure out what is the problem? Is it `Survival Tweaks` that is causing it?
```
11.02 19:13:26 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@236c93b9:
11.02 19:13:26 [Server] INFO java.lang.NullPointerException
11.02 19:13:26 [Server] INFO at thaumcraft.common.blocks.basic.BlockTable.func_180639_a(BlockTable.java:64) ~[BlockTable.class:?]
11.02 19:13:26 [Server] INFO at sorazodia.survival.mechanics.PlayerActionEvent.blockRightClick(PlayerActionEvent.java:124) ~[PlayerActionEvent.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_575_PlayerActionEvent_blockRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) [ForgeHooks.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) [lv.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) [me.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [jj.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [jj.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
11.02 19:13:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
11.02 19:13:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
11.02 19:13:26 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
11.02 19:13:26 [Server] Server thread/ERROR [FML]: Index: 17 Listeners:
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 0: HIGHEST
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 1: ASM: com.attributestudios.wolfarmor.event.WolfArmorPlayerEventHandler@480f78b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 2: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@612e4086 bedClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 3: NORMAL
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 4: ASM: class vazkii.botania.common.block.string.BlockRedStringInterceptor onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 5: ASM: vazkii.botania.common.item.material.ItemManaResource@71d22366 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 6: ASM: class vazkii.botania.common.item.relic.ItemLokiRing onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 7: ASM: com.animania.events.ItemSeedHandler@2189c468 notify(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 8: ASM: vazkii.quark.vanity.feature.SitInStairs@d43a6b3 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 9: ASM: vazkii.quark.tweaks.feature.DeployLaddersDown@20f45be6 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 10: ASM: vazkii.quark.tweaks.feature.RemoveSnowLayers@4cb01bb5 onPlayerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 11: ASM: vazkii.quark.tweaks.feature.RightClickSignEdit@7e5b76a1 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 12: ASM: biomesoplenty.common.handler.GrassPathEventHandler@63494c10 onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 13: ASM: class team.chisel.common.item.ChiselController onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 14: ASM: com.mrdimka.hammercore.event.TileHandler@599729dd playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 15: ASM: mods.railcraft.common.carts.MinecartHooks@29779ec3 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 16: ASM: com.pam.harvestcraft.addons.RightClickHarvesting@af0743a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 17: ASM: sorazodia.survival.mechanics.PlayerActionEvent@51851cec blockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 18: ASM: thaumcraft.common.lib.events.ToolEvents@7a905042 playerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 19: ASM: toughasnails.handler.thirst.FillBottleHandler@6f3e6dd7 onRightClickCauldron(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 20: ASM: mod.chiselsandbits.events.EventPlayerInteract@7db7b145 interaction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 21: ASM: com.enderio.core.common.handlers.RightClickCropHandler@50801fcc handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 22: ASM: mcmultipart.item.PartPlacementWrapper@1227201e onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 23: ASM: mcmultipart.item.PartPlacementWrapper@55b4baa5 onPlayerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 24: ASM: flaxbeard.cyberware.common.handler.EssentialsMissingHandler@46135cb0 handleRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 25: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@106d317c playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 26: ASM: com.pau101.fairylights.server.ServerEventHandler@343d7b8a onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 27: ASM: shetiphian.platforms.common.misc.EventHandler@6db3608c playerRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 28: ASM: zmaster587.advancedRocketry.event.PlanetEventHandler@5320bd21 blockPlaceEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 29: ASM: slimeknights.tconstruct.tools.ToolEvents@7bb561a4 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 30: ASM: betterwithmods.event.BucketEvent@7c5b853b fluidContainerUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 31: ASM: betterwithmods.event.LogHarvestEvent@20eec178 debarkLog(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 32: ASM: iguanaman.hungeroverhaul.module.event.HungerOverhaulEventHook@32d6f646 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 33: ASM: biomesoplenty.common.handler.AchievementEventHandler@2b3907e9 onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 34: ASM: WayofTime.bloodmagic.util.handler.event.LivingArmourHandler@7e848823 onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 35: ASM: WayofTime.bloodmagic.util.handler.event.GenericHandler@1d85dff7 onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 36: ASM: minetweaker.mc1102.ForgeEventHandler@155886da onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 37: ASM: toughasnails.handler.AchievementEventHandler@4993526e onItemUsed(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 38: ASM: appeng.parts.PartPlacement@1934de0e playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 39: ASM: pl.asie.computronics.integration.forestry.nanomachines.SwarmProvider@6c039d1c onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 40: ASM: CoroUtil.forge.EventHandlerForge@1c45eec2 blockPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 41: ASM: sonar.core.SonarEvents@6c9c5978 playerInteracts(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 42: ASM: ZombieAwareness.ZAEventHandler@3a874cb1 interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 43: LOW
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 44: ASM: codechicken.multipart.minecraft.EventHandler@5064bb93 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 45: LOWEST
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 46: ASM: flaxbeard.immersivepetroleum.common.EventHandler@253741d9 handlePickupItem(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/ERROR [FML]: 47: ASM: elec332.core.main.ElecCore$1@68a3753d onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
11.02 19:13:26 [Server] Server thread/FATAL Error executing task
11.02 19:13:26 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException
11.02 19:13:26 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
11.02 19:13:26 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
11.02 19:13:26 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
11.02 19:13:26 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
11.02 19:13:26 [Server] INFO Caused by: java.lang.NullPointerException
11.02 19:13:26 [Server] INFO at thaumcraft.common.blocks.basic.BlockTable.func_180639_a(BlockTable.java:64) ~[BlockTable.class:?]
11.02 19:13:26 [Server] INFO at sorazodia.survival.mechanics.PlayerActionEvent.blockRightClick(PlayerActionEvent.java:124) ~[PlayerActionEvent.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_575_PlayerActionEvent_blockRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
11.02 19:13:26 [Server] INFO at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026) ~[ForgeHooks.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435) ~[lv.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
11.02 19:13:26 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
11.02 19:13:26 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
11.02 19:13:26 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
11.02 19:13:26 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
11.02 19:13:26 [Server] INFO ... 5 more
```

**Comment by Azanor** [comment]
It does indeed seem to be breaking things.

**Comment by rgz0** [comment]
I can confirm that removing `Survival Tweaks` was making that issue, as it changes the way the player interacts with blocks when right-clicking. Removing the mod fixed the issue.

**Comment by serialtasted** [comment]
SoraZodia has promoted this issue as a bug. It might be fixed from is side? We'll see
https://github.com/SoraZodia/Survival-Tweaks/issues/18
