### ISSUE TITLE
[Beta5]game crash when Salis Mundus Right click Cauldron

### ISSUE THREAD

**Issue by anyijun** [Azanor/thaumcraft-beta#275]
[crash-2018-02-14_18.02.00-client.txt](https://github.com/Azanor/thaumcraft-beta/files/1723446/crash-2018-02-14_18.02.00-client.txt)

**Comment by ghbgh** [comment]
Also crashed when right click on a door

**Comment by twothe** [comment]
Same here, game crashes immediately when using Salis Mundus on a cauldron. I did not have this issue with B4, so my guess is that it was introduced with B5.

```
java.lang.IllegalArgumentException: Stack can not be null!
	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:434)
	at thaumcraft.common.lib.crafting.DustTriggerOre.getValidFace(DustTriggerOre.java:31)
	at thaumcraft.common.items.resources.ItemMagicDust.onItemUseFirst(ItemMagicDust.java:50)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:399)
```

**Comment by MainFreak** [comment]
Could you [gist](https://gist.github.com) the whole crashlog please?

I will test this later.
