### ISSUE TITLE
[B6] FTB Utils Use seal crash

### ISSUE THREAD

**Issue by fehrnah** [Azanor/thaumcraft-beta#319]
While having FTB Utils installed, having a 'use seal' used by a golem crashes the game.
 

```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2/17/18 1:34 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:97)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:877)
	at com.feed_the_beast.ftbl.lib.util.ServerUtils.isOP(ServerUtils.java:213)
	at com.feed_the_beast.ftbu.ranks.Ranks.getRank(Ranks.java:79)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.getRank(FTBUtilitiesAPI_Impl.java:55)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.hasPermission(FTBUtilitiesAPI_Impl.java:78)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.feed_the_beast.ftbu.FTBUPermissions.canModifyBlock(FTBUPermissions.java:143)
	at com.feed_the_beast.ftbu.api_impl.ClaimedChunkStorage.canPlayerInteract(ClaimedChunkStorage.java:91)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onRightClickBlock(FTBUPlayerEventHandler.java:218)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_FTBUPlayerEventHandler_onRightClickBlock_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026)
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435)
	at thaumcraft.common.entities.construct.golem.seals.SealUse.onTaskCompletion(SealUse.java:127)
	at thaumcraft.common.entities.construct.golem.tasks.TaskHandler.completeTask(TaskHandler.java:110)
	at thaumcraft.common.entities.construct.golem.ai.AIGoto.func_75246_d(AIGoto.java:120)
	at thaumcraft.common.entities.construct.golem.ai.AIGotoBlock.func_75246_d(AIGotoBlock.java:25)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70636_d(EntityThaumcraftGolem.java:260)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at thaumcraft.common.entities.construct.EntityOwnedConstruct.func_70071_h_(EntityOwnedConstruct.java:121)
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70071_h_(EntityThaumcraftGolem.java:272)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:51)
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9)
	at net.minecraft.server.management.UserList.func_152692_d(SourceFile:97)
	at net.minecraft.server.management.PlayerList.func_152596_g(PlayerList.java:877)
	at com.feed_the_beast.ftbl.lib.util.ServerUtils.isOP(ServerUtils.java:213)
	at com.feed_the_beast.ftbu.ranks.Ranks.getRank(Ranks.java:79)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.getRank(FTBUtilitiesAPI_Impl.java:55)
	at com.feed_the_beast.ftbu.api_impl.FTBUtilitiesAPI_Impl.hasPermission(FTBUtilitiesAPI_Impl.java:78)
	at net.minecraftforge.server.permission.PermissionAPI.hasPermission(PermissionAPI.java:84)
	at com.feed_the_beast.ftbu.FTBUPermissions.canModifyBlock(FTBUPermissions.java:143)
	at com.feed_the_beast.ftbu.api_impl.ClaimedChunkStorage.canPlayerInteract(ClaimedChunkStorage.java:91)
	at com.feed_the_beast.ftbu.handlers.FTBUPlayerEventHandler.onRightClickBlock(FTBUPlayerEventHandler.java:218)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_42_FTBUPlayerEventHandler_onRightClickBlock_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1026)
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:435)
	at thaumcraft.common.entities.construct.golem.seals.SealUse.onTaskCompletion(SealUse.java:127)
	at thaumcraft.common.entities.construct.golem.tasks.TaskHandler.completeTask(TaskHandler.java:110)
	at thaumcraft.common.entities.construct.golem.ai.AIGoto.func_75246_d(AIGoto.java:120)
	at thaumcraft.common.entities.construct.golem.ai.AIGotoBlock.func_75246_d(AIGotoBlock.java:25)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70636_d(EntityThaumcraftGolem.java:260)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at thaumcraft.common.entities.construct.EntityOwnedConstruct.func_70071_h_(EntityOwnedConstruct.java:121)
	at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70071_h_(EntityThaumcraftGolem.java:272)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: thaumcraft.Golem (thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem)
	Entity ID: 19778
	Entity Name: Golem
	Entity's Exact location: 843.75, 56.00, 337.53
	Entity's Block location: World: (843,56,337), Chunk: (at 11,3,1 in 52,21; contains blocks 832,0,336 to 847,255,351), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.11, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['kalak35'/1, l='New World', x=840.20, y=56.00, z=336.80]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4376332960945361124
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,3*minecraft:stone,52*minecraft:sandstone;2;
	Level spawn location: World: (845,4,344), Chunk: (at 13,0,8 in 52,21; contains blocks 832,0,336 to 847,255,351), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 1581 game time, 1581 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 103681 (now: false), thunder time: 168351 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1733679608 bytes (1653 MB) / 2277507072 bytes (2172 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJAAAA	compatlayer{0.3.1} [compatlayer] (compatlayer-1.10-0.3.1.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['kalak35'/1, l='New World', x=840.20, y=56.00, z=336.80]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by farigiss** [comment]
This was already posted https://github.com/Azanor/thaumcraft-beta/issues/191
