### ISSUE TITLE
B6 crash with Psionic Upgrades r1.15 addon for Psi r1.0-42

### ISSUE THREAD

**Issue by Enderborn1235** [Azanor/thaumcraft-beta#349]
It seems to be crashing due to the custom potions that Psionic Upgrades adds. Works fine with just the Psi addon and Psi itself.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/23/18 12:20 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: java.lang.ClassCastException: wiresegal.psionup.common.crafting.ModRecipes$potionPredicate$1 cannot be cast to net.minecraft.potion.PotionHelper$ItemPredicateInstance
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getPotionReagentsRecursive(ThaumcraftCraftingManager.java:426)
	at thaumcraft.common.config.ConfigAspects.getPotionAspects(ConfigAspects.java:628)
	at thaumcraft.common.config.ConfigAspects.registerItemAspects(ConfigAspects.java:467)
	at thaumcraft.common.config.ConfigAspects.postInit(ConfigAspects.java:23)
	at thaumcraft.proxies.CommonProxy.postInit(CommonProxy.java:142)
	at thaumcraft.proxies.ClientProxy.postInit(ClientProxy.java:65)
	at thaumcraft.Thaumcraft.postInit(Thaumcraft.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:810)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1436218784 bytes (1369 MB) / 2013265920 bytes (1920 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJ	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJ	Psi{r1.0-42} [Psi] (Psi-r1.0-42 (1).jar) 
	UCHIJ	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2 (1).jar) 
	UCHIJ	Baubles{1.3.13} [Baubles] (Baubles-1.10.2-1.3.13.jar) 
	UCHIJ	wizardry{2.1.2} [Electroblob's Wizardry] (Electroblob's+Wizardry+-+2.1.2+-+MC+1.10.2.jar) 
	UCHIJ	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420 (1).jar) 
	UCHIJ	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15 (3).jar) 
	UCHIE	thaumcraft{6.0.BETA6} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA6.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13492 Compatibility Profile Context 22.19.677.257' Renderer: 'Radeon (TM) RX 480 Graphics'

**Comment by Domiryuu** [comment]
Seems to be related to #327

**Comment by dariumz** [comment]
> It has been reported and will be fixed in the next release.
