### ISSUE TITLE
B6: CME server crash with Eldritch warden and Vampirism ghost

### ISSUE THREAD

**Issue by LemADEC** [Azanor/thaumcraft-beta#350]
As of Thaumcraft-1.10.2-6.0.BETA6.jar and Vampirism-1.10.2-1.2.4.jar, server crashes with ConcurrentModificationException when a Vampirism ghost is inside a Eldritch warden aura.

```
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:586)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:176)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityLivingBase.func_70679_bo(EntityLivingBase.java:586)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:343)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:176)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1937)

-- Entity being ticked --
Details:
	Entity Type: vampirism.ghost (de.teamlapen.vampirism.entity.EntityGhost)
	Entity ID: 393
	Entity Name: Ghost
	Entity's Exact location: 282,40, 72,00, 265,19
	Entity's Block location: World: (282,72,265), Chunk: (at 10,4,9 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0,08, -0,08, -0,12
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
```

Vampirism ghost will go invisible for 5 second when hit by an entity. This is done by applying the invisibility potion effect during the entity tick event.
Is Thaumcraft applying the aura potion effects at the same time but outside of the main thread?

Issue was reproduced in single player and on a dedicated server.

**Comment by Azanor** [comment]
I hate so say it, but I think the problem might be on the Vampirism side. 
The warden does add a potion effect, but it occurs the normal ranged mob attackEntityWithRangedAttack method which should be within the normal game loop. The projectiles it fires also add a potion effect, but once again that occurs when they hit something which is also (I assume) in the normal loop.
I suspect the that I add the potion effect to which the ghost instantly reacts by adding its own effect which then causes this issue.

**Comment by LemADEC** [comment]
Is it possible a network packet is involved in adding the potion? Since packets are multi-threaded, that would explain the issue.

@TeamLapen any thought on this?

**Comment by Azanor** [comment]
Nope, no packets.

**Comment by LemADEC** [comment]
According to the source code, Ghost directly reacts to an attack by adding invisibility potion. I'm confused on how that ends up in a CME.

**Comment by Azanor** [comment]
As a matter of course I have learned to put all my potion code in try catch blocks. The MC potion code does weird stuff sometimes.

**Comment by maxanier** [comment]
The weird thing is that the crash is caused from within the Entity#onUpdate -> updatePotions method. So there is seems to be no concurrent modification by Vampirism and Thaumcraft, but rather a concurrent modification by a mod (Vampirism or Thaumcraft) and the Vanilla update code.

Yes Potions are annoying, even a try catch would not really help here because the exception is thrown in the Vanilla update

Since this seems easily reproduce-able, I will try to debug it further when I have time

**Comment by LemADEC** [comment]
I can't reproduce by throwing poison potions at ghost.
I can reproduce with just Thaumcraft, Bauble and Vampirism.
When the crash happens, I've time to see the Ghost changing to red coloring.

**Comment by Azanor** [comment]
FYI the potion effect that is causing this is witheri, so this might actually be a strange vanilla interaction issue. This is a strange one.

**Comment by Azanor** [comment]
Nevermind, I think I found it. It is not the Warden, but the purple patches he leaves behind. They add damage and a potion effect when walked on which in theory happens outside the normal loops.
