### ISSUE TITLE
TC6 Beta 6 - can't place Golems

### ISSUE THREAD

**Issue by HiddenGambit1** [Azanor/thaumcraft-beta#358]
I have found a mod conflict that prevents the placements of Thaumcraft Golems.  

The conflicting mod is Mo'Creatures.  The exact mod names and versions are at the bottom.  I am not sure if it is a limitation in the Thaumcraft Beta or within Mo'Creatures itself.  The game does not crash; you just can't put the thaumcraft golems you make on the ground.

This is not a new limitation.  i saw this with the last beta version as well.

Mods combinations that cause a problem.
Minecraft 1.10.2
Thaumcraft - 1.10.2-6.0.BETA6
Baubles-1.10.2-1.3.13
DrZhark's Mo'Creatures Mod-10.0.6
CustomMobSpawner 3.10.1

**Comment by Azanor** [comment]
Have you reported this to the Mo'Creatures devs?

**Comment by HiddenGambit1** [comment]
I have not yet.  i will do so, sorry i didn't think to report to both mods.
Without a crash I wasn't sure how to actually tell which mod had the issue.  With trying to place a Thaumcraft Golem, this github was my first thought.

**Comment by Ormei** [comment]
Got the same issue. Golems, Arcane Bore and Advanced Crossbow cannot be placed. Only normal Crossbow seems to work. And this appears in the logs:
```
[02:14:53] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Duplicate id value for 16!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 16!
        at net.minecraft.network.datasync.EntityDataManager.func_187214_a(SourceFile:79) ~[kk.class:?]
        at thaumcraft.common.entities.construct.EntityTurretCrossbowAdvanced.func_70088_a(EntityTurretCrossbowAdvanced.java:86) ~[EntityTurretCrossbowAdvanced.class:?]
        at net.minecraft.entity.Entity.<init>(Entity.java:203) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:155) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) ~[sg.class:?]
        at net.minecraft.entity.EntityCreature.<init>(SourceFile:18) ~[sm.class:?]
        at thaumcraft.common.entities.construct.EntityOwnedConstruct.<init>(EntityOwnedConstruct.java:34) ~[EntityOwnedConstruct.class:?]
        at thaumcraft.common.entities.construct.EntityTurretCrossbow.<init>(EntityTurretCrossbow.java:59) ~[EntityTurretCrossbow.class:?]
        at thaumcraft.common.entities.construct.EntityTurretCrossbowAdvanced.<init>(EntityTurretCrossbowAdvanced.java:50) ~[EntityTurretCrossbowAdvanced.class:?]
        at thaumcraft.common.entities.construct.EntityTurretCrossbowAdvanced.<init>(EntityTurretCrossbowAdvanced.java:76) ~[EntityTurretCrossbowAdvanced.class:?]
        at thaumcraft.common.entities.construct.ItemTurretPlacer.onItemUseFirst(ItemTurretPlacer.java:75) ~[ItemTurretPlacer.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:439) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by Azanor** [comment]
Unfortunately this is not a bug I can fix - Mo'Creatures is using up all the datawatcher id's

**Comment by Ormei** [comment]
Just tested the new Beta10 with Mo Creatures on Minecraft 1.12.2. Golems and Arcane Bore are placeable now. But Advanced Crossbow still does not work.

**Comment by Teirdalin** [comment]
Ehh,  can confirm doesn't work with latest version of Thaumcraft(6.1.BETA26) and MoCreatures(12.0.5).   Crashes clients on my server once a golem gets placed;  problems fixed once Mo Creatures was removed.  (Didn't crash server though, just client after locking it up)    Will make a post onto the MoCreatures github about it.
