### ISSUE TITLE
B6 - player can't connect if they didn't sleep after getting crystals

### ISSUE THREAD

**Issue by LemADEC** [Azanor/thaumcraft-beta#369]
As of Beta6, when a player get initial hint from crystals, then disconnect before sleeping, he/she'll no longer be able to connect to a dedicated server.

There's a long chain of thaumcraft.common.lib.events.PlayerEvents.wakeUp related exception, that leads to this final one before kicking the player:
```
[17:30:39] [Server thread/WARN]: Failed to handle packet for /xxxxx:56680
net.minecraft.util.ReportedException: Loading entity NBT
>       at net.minecraft.entity.Entity.func_70020_e(Entity.java:1716) ~[rw.class:?]
>       at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:222) ~[azy.class:?]
>       at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:322) ~[mp.class:?]
>       at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1428) ~[mp.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
>       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
>       at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:3741) ~[lu.class:?]
>       at org.spongepowered.api.text.channel.MessageChannel.lambda$send$3(MessageChannel.java:196) ~[MessageChannel.class:1.10.2-2477-5.2.0-BETA-2793]
>       at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
>       at org.spongepowered.api.text.channel.MessageChannel.send(MessageChannel.java:196) ~[MessageChannel.class:1.10.2-2477-5.2.0-BETA-2793]
>       at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:58) ~[ChatUtil.class:1.10.2-2477-5.2.0-BETA-2793]
>       at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(EntityPlayerMP.java:3755) ~[lu.class:?]
>       at thaumcraft.common.lib.events.PlayerEvents.wakeUp(PlayerEvents.java:123) ~[PlayerEvents.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_576_PlayerEvents_wakeUp_PlayerWakeUpEvent.invoke(.dynamic) ~[?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632) ~[EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588) ~[EventBus.class:?]
>       at net.minecraftforge.event.ForgeEventFactory.onPlayerWakeup(ForgeEventFactory.java:447) ~[ForgeEventFactory.class:?]
>       at net.minecraft.entity.player.EntityPlayer.func_70999_a(EntityPlayer.java:4094) ~[zs.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_70999_a(EntityPlayerMP.java:653) ~[lu.class:?]
>       at net.minecraft.entity.player.EntityPlayer.func_70037_a(EntityPlayer.java:905) ~[zs.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_70037_a(EntityPlayerMP.java:178) ~[lu.class:?]
>       at net.minecraft.entity.Entity.func_70020_e(Entity.java:1704) ~[rw.class:?]
>       ... 13 more
[17:30:39] [Server thread/INFO]: xxxx lost connection: Internal server error
```

Manually removing the crystal knowledge from its player data fixed it.

**Comment by LemADEC** [comment]
Issue isn't reproduced in single player.

**Comment by Azanor** [comment]
Looks like shenanigens caused by spongepowered, but I will try and catch the exception on my side.
