### ISSUE TITLE
Crash in Items Intervace e.g. Chest

### ISSUE THREAD

**Issue by yotthani** [Azanor/thaumcraft-beta#40]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/18/17 8:52 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getBonusTags(ThaumcraftCraftingManager.java:410)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:276)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:224)
	at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java:313)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_946_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:795)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:529)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getBonusTags(ThaumcraftCraftingManager.java:410)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:276)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:224)
	at thaumcraft.client.lib.events.RenderEventHandler.tooltipEvent(RenderEventHandler.java:313)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_946_RenderEventHandler_tooltipEvent_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:795)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:529)

-- Screen render details --
Details:
	Screen name: slimeknights.tconstruct.smeltery.client.GuiSmeltery
	Mouse location: Scaled: (524, 290). Absolute: (1049, 415)
	Screen size: Scaled: (960, 498). Absolute: (1920, 996). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['yotthani'/233256, l='MpServer', x=253.23, y=72.00, z=-14.77]]
	Chunk stats: MultiplayerChunkCache: 169, 169
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (216,64,248), Chunk: (at 8,4,8 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 43051652 game time, 1316005 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 201 total; [MoCEntityThrowableRock['entity.mocreatures.TRock.name'/10242, l='MpServer', x=305.65, y=69.00, z=-18.88], EntityRoosterRhodeIslandRed['Rhode Island Red Rooster'/10243, l='MpServer', x=305.89, y=71.73, z=-22.48], EntityConcussionCreeper['Concussion Creeper'/417285, l='MpServer', x=191.50, y=70.00, z=-4.50], MoCEntityAnchovy['Anchovy'/238599, l='MpServer', x=530.

**Comment by Azanor** [comment]
Looks like one of the mods you are using adds a buggy enchantment.  I've put in a test to prevent this crash in the future, but someone else is definitely being a bit naughty with their mod :)

**Comment by yotthani** [comment]
ok thx, had teared it down to any enchanted item moved by shift + left click causing the crash ..
