### ISSUE TITLE
B8:  Golemancy issues

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#425]
1.  Golemancy -> USE seal:
"If a whitelist **items is** specified..."

2.  I cannot place golems in B8.  Trying to place any golem results in the following error:

[14:35:44] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Duplicate id value for 16!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 16!
        at net.minecraft.network.datasync.EntityDataManager.func_187214_a(SourceFile:79) ~[kk.class:?]
        at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.func_70088_a(EntityThaumcraftGolem.java:97) ~[EntityThaumcraftGolem.class:?]
        at net.minecraft.entity.Entity.<init>(Entity.java:203) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:155) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) ~[sg.class:?]
        at net.minecraft.entity.EntityCreature.<init>(SourceFile:18) ~[sm.class:?]
        at thaumcraft.common.entities.construct.EntityOwnedConstruct.<init>(EntityOwnedConstruct.java:34) ~[EntityOwnedConstruct.class:?]
        at thaumcraft.common.entities.construct.golem.EntityThaumcraftGolem.<init>(EntityThaumcraftGolem.java:70) ~[EntityThaumcraftGolem.class:?]
        at thaumcraft.common.entities.construct.golem.ItemGolemPlacer.onItemUseFirst(ItemGolemPlacer.java:102) ~[ItemGolemPlacer.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:439) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

**Comment by UnixRonin** [comment]
Golems still unplaceable with the updated/rebuilt Beta 8.

**Comment by Azanor** [comment]
Yeah, that error occurs if something adds datawatchers to base entities above and beyond what vanilla already adds - there is only a limited number of datawatchers allowed (16) and golems use several themselves.

Not much I can do about this unfortunately.

**Comment by UnixRonin** [comment]
Yup, about the only thing that can be done there is document the conflict, short of patching Minecraft itself to increase the allowed datawatchers.
