### ISSUE TITLE
[B10] B10 kills Botania (fixed in Botania 354+ builds)

### ISSUE THREAD

**Issue by CurePindal** [Azanor/thaumcraft-beta#477]
Edit: The Botania team already fixed it in the latest commits. Fixed versio is already released.

Running B10 makes Botania 353 crash on startup. This private modpack runs fine either with B10 or Botania. (Sad Panda now. Was preparing this pack for the arrival of TC6 on 1.12.2. Guess I have to play Battletech today instead 😀 )

This is the issue on B9: https://github.com/Azanor/thaumcraft-beta/issues/468

```
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (SmoothFont-1.12.2-1.15-b1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 4/24/18 2:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Botania (botania)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: vazkii.botania.common.item.equipment.bauble.ItemBauble
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:578)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: vazkii.botania.common.item.equipment.bauble.ItemBauble
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/items/IRunicArmor
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 42 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.api.items.IRunicArmor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 46 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 189934312 bytes (181 MB) / 469954560 bytes (448 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2669 Optifine OptiFine_1.12.2_HD_U_D1 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                        | Signature                                |
	|:----- |:------------------------ |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UC    | mcp                      | 9.42                     | minecraft.jar                                 | None                                     |
	| UC    | FML                      | 8.0.99.99                | forge-1.12.2-14.23.3.2669.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                    | 14.23.3.2669             | forge-1.12.2-14.23.3.2669.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | smoothfontcore           | 1.12.2-1.14              | minecraft.jar                                 | None                                     |
	| UC    | smoothfont               | 1.12.2-1.15-b1           | SmoothFont-1.12.2-1.15-b1.jar                 | None                                     |
	| UC    | charcoal_pit             | 1.13.3                   | CharcoalPit-[1.12]-1.13.3.jar                 | None                                     |
	| UC    | jei                      | 4.9.0.163                | jei_1.12.2-4.9.0.163.jar                      | None                                     |
	| UC    | abyssalcraft             | 1.9.4.8                  | AbyssalCraft-1.12.2-1.9.4.8.jar               | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UC    | aether_legacy            | 1.12.2-v3.0              | aether_legacy-1.12.2-v3.0.jar                 | None                                     |
	| UC    | infinitylib              | 1.12.2-1.12.0            | infinitylib-1.12.0.jar                        | None                                     |
	| UC    | agricraft                | 2.12.0-1.12.0-a4         | agricraft-2.12.0-1.12.0-a4.jar                | None                                     |
	| UC    | antiqueatlas             | 4.4.7                    | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UC    | antiqueatlasoverlay      | 1.2                      | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UC    | examplemod               | 1.0                      | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UC    | astralsorcery            | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                | None                                     |
	| UC    | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UC    | betterunderground        | 1.1.2                    | betterunderground-1.1.2.jar                   | None                                     |
	| UC    | bibliocraft              | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UC    | forestry                 | 5.8.0.270                | forestry_1.12.2-5.8.0.270.jar                 | None                                     |
	| UC    | binniecore               | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | binniedesign             | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | genetics                 | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | botany                   | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | extrabees                | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | extratrees               | 2.5.0.163                | binnie-mods-1.12.2-2.5.0.163.jar              | None                                     |
	| UC    | biomesoplenty            | 7.0.1.2361               | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
	| UC    | thaumcraft               | 6.1.BETA10               | Thaumcraft-1.12.2-6.1.BETA10.jar              | None                                     |
	| UE    | botania                  | r1.10-353                | Botania+r1.10-353.jar                         | None                                     |
	| UC    | chesttransporter         | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
	| UC    | chococraft               | 0.9.1.52                 | chococraft_1.12.1-0.9.1.52.jar                | None                                     |
	| UC    | codechickenlib           | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | coralreef                | 2.0                      | CoralReef-2.4-1.12.2.jar                      | None                                     |
	| UC    | craftablesaddles         | 1.3                      | Craftable+Saddles[1.12]-1.3.jar               | None                                     |
	| UC    | cyclopscore              | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                 | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | dimdoors                 | 3.0.8+271                | DimensionalDoors-3.0.8-271.jar                | None                                     |
	| UC    | dsurround                | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar       | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UC    | presets                  | 3.4.9.11                 | DynamicSurroundings-1.12.2-3.4.9.11.jar       | None                                     |
	| UC    | eleccore                 | 1.8.434                  | ElecCore-1.12.2-1.8.434.jar                   | None                                     |
	| UC    | erebus                   | 1.0.22                   | Erebus-1.0.22.jar                             | None                                     |
	| UC    | evilcraft                | 0.10.55                  | EvilCraft-1.12.2-0.10.55.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UC    | evilcraftcompat          | 1.0.0                    | EvilCraft-1.12.2-0.10.55.jar                  | None                                     |
	| UC    | fastleafdecay            | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| UC    | runesofwizardry          | 1.12.2-0.8.8             | Runes-of-Wizardry-1.12.2-0.8.8.jar            | None                                     |
	| UC    | guideapi                 | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
	| UC    | waila                    | 1.8.25                   | Hwyla-1.8.25-B40_1.12.jar                     | None                                     |
	| UC    | llibrary                 | 1.7.9                    | llibrary-1.7.9-1.12.2.jar                     | None                                     |
	| UC    | iceandfire               | 1.4.0                    | iceandfire-1.4.0-1.12.2.jar                   | None                                     |
	| UC    | infernalmobs             | 1.7.5                    | InfernalMobs-1.12.2.jar                       | None                                     |
	| UC    | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest                | 1.12.2-7.0.42.827        | ironchest-1.12.2-7.0.42.827.jar               | None                                     |
	| UC    | harvestcraft             | 1.12.2t                  | Pam's+HarvestCraft+1.12.2t.jar                | None                                     |
	| UC    | jehc                     | 1.12.2                   | JEHC-1.12.2-1.5.0.0.jar                       | None                                     |
	| UC    | jeibees                  | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                  | None                                     |
	| UC    | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UC    | magicbees                | 1.0                      | MagicBees-1.12.2-3.1.9.jar                    | None                                     |
	| UC    | nei                      | 2.4.1                    | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | petbat                   | 1.4.7                    | PetBat-1.12.jar                               | None                                     |
	| UC    | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| UC    | runesofwizardry_classics | 1.12.2-0.5.6             | RunesofWizardry-Classics-1.12.2-0.5.6.jar     | None                                     |
	| UC    | stepup                   | 1.0-mc1.10-1.12.2        | StepUp-1.0-mc1.10-1.12.2.jar                  | None                                     |
	| UC    | thebetweenlands          | 3.3.7                    | TheBetweenlands-3.3.7-universal.jar           | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UC    | totemic                  | 1.12.2-0.11.0            | Totemic-1.12.2-0.11.0.jar                     | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UC    | twilightforest           | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |
	| UC    | wawla                    | 2.5.253                  | Wawla-1.12.2-2.5.253.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
CorePlugin (SmoothFont-1.12.2-1.15-b1.jar)
  bre.smoothfont.asm.Transformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.11.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'`


```

**Comment by CurePindal** [comment]
Yes, dear Sir! Seems they already made a hotfix commit: https://github.com/Vazkii/Botania/issues/2608
Wasnt aware on which end this problem might have been!
Keep up the amazing work! =)

**Comment by warplord** [comment]
I am having the same issue - hope it is resolved soon, would be nasty to have to choose between these mods.

**Comment by CurePindal** [comment]
Azanor and Team already fixed it in the latest commits. If you build from source its working again.

**Comment by MokahTGS** [comment]
New release of Botania on Curse fixes this issue.
