### ISSUE TITLE
[B8] Moon celestial research not working

### ISSUE THREAD

**Issue by UntoldForce** [Azanor/thaumcraft-beta#490]
I followed the beta 7 issue where people on servers were unable to get lunar celestial research. I am experiencing the same issue with beta 8.

Minecraft: 1.10.2
Forge: 12.18.3.2422
CompatLayer: 0.2.9
Thaumcraft-1.10.2-6.0.BETA8.jar
Baubles-1.10.2-1.3.13.jar
+about 200 other mods, including Astral Sorcery. If you want a full list I can post it.

The server is throwing the following error every time I try to scan the moon. I can scan the sun without an issue.

> [19:13:05] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.World.func_72853_d()I
	at thaumcraft.common.lib.research.ScanSky.onSuccess(ScanSky.java:80) ~[ScanSky.class:?]
	at thaumcraft.api.research.ScanningManager.scanTheThing(ScanningManager.java:48) ~[ScanningManager.class:?]
	at thaumcraft.common.items.tools.ItemThaumometer.doScan(ItemThaumometer.java:137) ~[ItemThaumometer.class:?]
	at thaumcraft.common.items.tools.ItemThaumometer.func_77659_a(ItemThaumometer.java:53) ~[ItemThaumometer.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:365) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:710) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[jk.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[jk.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

**Comment by laserlemons** [comment]
Not getting this error on B10 1.12.2.

**Comment by rYanGap** [comment]
I'm in a 1.10.2 modpack, so I can't attest to the status on 1.12.2
