### ISSUE TITLE
Crashed when opened a tinker table from mystical agriculture

### ISSUE THREAD

**Issue by vdrake77** [Azanor/thaumcraft-beta#495]
Thaumcraft B10
Minecraft 1.12.2
Forge 2673

Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at thaumcraft.api.crafting.ShapelessArcaneRecipe.func_77569_a(ShapelessArcaneRecipe.java:60)
	at assets.recipehandler.CraftingHandler.getCrafts(CraftingHandler.java:175)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:263)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_191745_a(GuiEventHandler.java:130)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:70)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:80)
	at com.blakebr0.mysticalagriculture.gui.GuiTinkeringTable.func_73863_a(GuiTinkeringTable.java:25)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:636)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thaumcraft.api.crafting.ShapelessArcaneRecipe.func_77569_a(ShapelessArcaneRecipe.java:60)
	at assets.recipehandler.CraftingHandler.getCrafts(CraftingHandler.java:175)
	at assets.recipehandler.CraftingHandler.getNumberOfCraft(CraftingHandler.java:263)
	at assets.recipehandler.GuiEventHandler$CreativeButton.func_191745_a(GuiEventHandler.java:130)
	at net.minecraft.client.gui.GuiScreen.func_73863_a(GuiScreen.java:70)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:80)
	at com.blakebr0.mysticalagriculture.gui.GuiTinkeringTable.func_73863_a(GuiTinkeringTable.java:25)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:636)

-- Screen render details --
Details:
	Screen name: com.blakebr0.mysticalagriculture.gui.GuiTinkeringTable
	Mouse location: Scaled: (256, 139). Absolute: (1280, 693)
	Screen size: Scaled: (512, 278). Absolute: (2560, 1387). Scale factor of 5

Crashed as soon as I tried to open that table.  Not even sure why thaumcraft was involved.

**Comment by Azanor** [comment]
I suspect the bug is on their side - they are passing a null itemstack which is a big nono. I will catch the error, but you should report it to that mods authors as well.

**Comment by vdrake77** [comment]
-    private ItemStack result;
+    private ItemStack result = ItemStack.EMPTY;

Is what he changed on his end.  Is that a fix?  Got no real idea how java code works
