### ISSUE TITLE
[B11] Persistent crash on startup.

### ISSUE THREAD

**Issue by Lord-Giratina** [Azanor/thaumcraft-beta#534]
I've tried everything I can think of to fix this but It just keeps crashing, So I figured id post it here, since it seems to be thaumcraft related. Apologies in advance if its unrelated.

[net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-81.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-77.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  AstralCore (astralsorcery-1.12.2-1.8.8.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.174.jar)
  llibrary (llibrary-1.7.9-1.12.2.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.1.0.3.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.1.4-universal.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.6-core.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.3.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Wizardry Plugin (wizardry-0.8.5.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.3.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 4/26/18 11:45 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thaumcraft (thaumcraft)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:578)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:280)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:149)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:603)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getConstructor0(Class.java:3067)
	at java.lang.Class.getConstructor(Class.java:1817)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer sereneseasons.asm.transformer.EntityRendererTransformer@7e34edaf from coremod SSLoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 46 more
Caused by: java.lang.RuntimeException: No method instruction node found matching anh canRain ()Z
	at sereneseasons.asm.ASMHelper.getUniqueMethodInsnNode(ASMHelper.java:75)
	at sereneseasons.asm.transformer.EntityRendererTransformer.transformEntityRenderer(EntityRendererTransformer.java:139)
	at sereneseasons.asm.transformer.EntityRendererTransformer.transform(EntityRendererTransformer.java:34)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 48 more

**Comment by Lord-Giratina** [comment]
Yep, Removing Serene Seasons fixed it. Id guess it was trying to change the leaves on the TC Trees. Issue Closed I guess.
