### ISSUE TITLE
[B11] Index out of bounds exception and client crash when mousing over recipes in Thaumonomicon

### ISSUE THREAD

**Issue by UnixRonin** [Azanor/thaumcraft-beta#553]
If I open a crafting recipe tab in the Thaumonomicon, then mouse over the recipe, I get a client-side crash on an out of bounds exception:

java.lang.ArrayIndexOutOfBoundsException: 1
        at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
        at thaumcraft.client.gui.GuiResearchPage.drawArcaneCraftingPage(GuiResearchPage.java:1432)
        at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1037)
        at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
        at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
        at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
        at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at Reflector.callVoid(Reflector.java:636)
        at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**As long as I don't mouse over the recipe,** I am fine.

**Comment by EnderofGames** [comment]
#519 

Try making sure you are using a clean save from your update from B10.

**Comment by Mike-U5** [comment]
@EnderofGames I did create a clean save and I have the crash too. Not using any mods besides Thaumcraft and Baubles either.

**Comment by Lordmau5** [comment]
Clean save here, too. Same issue.
Happening on a dedicated server in case that helps out with the issue.

The highlighted part clearly assumes that `sr[1]` is **always** available.
Not the best thing to do...
![image](https://user-images.githubusercontent.com/1345036/39407746-45bf609e-4bcb-11e8-88be-9e58691ecf5e.png)

**Comment by UnixRonin** [comment]
I believe you've nailed it, @LordMau5.
