### ISSUE TITLE
[B10] Server Crash running away from Cultists [java.lang.NullPointerException: The validated object is null]

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-beta#589]
Another crash while running away from cultists spawning from a portal, this was after blinding running at it to scan with the thaumometer, saw both a knight and a mage spawn, scanned each really quick and ran away screaming, then the server crashed, my guess is maybe the fireball from the mage hit the knight? because I have dealt with them individually before and had no crashes

[crash-2018-04-30_12.32.09-server.txt](https://github.com/Azanor/thaumcraft-beta/files/1960532/crash-2018-04-30_12.32.09-server.txt)

**Comment by the-realest-stu** [comment]
I get the same type of error with arcane bores in beta 11.

java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.util.NonNullList.set(SourceFile:49)
	at net.minecraft.entity.EntityLiving.func_184201_a(EntityLiving.java:1060)
	at net.minecraft.entity.EntityLivingBase.func_184611_a(EntityLivingBase.java:1639)
	at thaumcraft.common.entities.construct.EntityArcaneBore.dig(EntityArcaneBore.java:300)
	at thaumcraft.common.entities.construct.EntityArcaneBore.func_70071_h_(EntityArcaneBore.java:142)
	at repose.entity.item.EntityFallingBlockExtensions$.onUpdate(EntityFallingBlockExtensions.scala:92)
	at repose.entity.item.EntityFallingBlockExtensions.onUpdate(EntityFallingBlockExtensions.scala)
	at net.minecraft.world.World.func_72866_a(World.java:1990)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
