### ISSUE TITLE
Client Crash when opening Recipie Page

### ISSUE THREAD

**Issue by clubpetey** [Azanor/thaumcraft-beta#597]
Lots of mods, no OptiFine.  Attemped to open the Yellow Nitor page in the Thauminomicon.

Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 1
	at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
	at thaumcraft.client.gui.GuiResearchPage.drawCruciblePage(GuiResearchPage.java:1555)
	at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1043)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Levitikan** [comment]
i'm getting this problem as well with
java.lang.ArrayIndexOutOfBoundsException: 1
as an error, not using optifine and using the ATM3 mod pack

**Comment by ProxyPlayerHD** [comment]
Same bug, it only seems to happen when i hover over the glowstone dust in the Nitor Recipe

LOG: https://pastebin.com/EKPcSMfW

using Optifine, selfmade pack

also glass doesn't have transparecny anymore, they are just full colored blocks, except when i turn off the resourcepack for some reason.

**Comment by 0uti** [comment]
same here.
no optifine, custom modpack.

https://pastebin.com/PCjuARs7

**Comment by reinder-s** [comment]
its a know issue thats being worked on
