### ISSUE TITLE
Hovering cursor over glowstone in Alchemy entry in Thaumonomicon causes crash.

### ISSUE THREAD

**Issue by talonos2** [Azanor/thaumcraft-beta#614]
1: Enter the Alchemy Entry.
2: Click the tab that has the recipe for nitor
3: Hover your cursor over the glowstone
4: Clientside crash.

![alchemycrash](https://user-images.githubusercontent.com/3359830/39561731-c6b28910-4e64-11e8-98b4-4e1c67388cc3.gif)

```
// Ouch. That hurt :(

Time: 5/2/18 11:51 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 1
	at thaumcraft.client.gui.GuiResearchPage.drawStackAt(GuiResearchPage.java:2035)
	at thaumcraft.client.gui.GuiResearchPage.drawCruciblePage(GuiResearchPage.java:1555)
	at thaumcraft.client.gui.GuiResearchPage.drawRecipe(GuiResearchPage.java:1043)
	at thaumcraft.client.gui.GuiResearchPage.drawPage(GuiResearchPage.java:465)
	at thaumcraft.client.gui.GuiResearchPage.genResearchBackground(GuiResearchPage.java:321)
	at thaumcraft.client.gui.GuiResearchPage.func_73863_a(GuiResearchPage.java:261)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by talonos2** [comment]
Look like this is a duplicate of #514.
