### ISSUE TITLE
Baubles xp issue

### ISSUE THREAD

**Issue by sabrael** [Azanor/thaumcraft-beta#70]
Fresh game, using baubles-1.10.2-1.3.9 and Thaumcraft-1.10.2-6.0.BETA0. Spawned by some sheep, punched one to death and crashed when I walked over the experience orb.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/15/18 3:57 PM
Description: Ticking player

java.lang.NoSuchMethodError: baubles.api.BaublesApi.isBaubleEquipped(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/item/Item;)I
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 777
	Entity Name: bendicott06
	Entity's Exact location: 191.10, 64.00, 214.98
	Entity's Block location: World: (191,64,214), Chunk: (at 15,4,6 in 11,13; contains blocks 176,0,208 to 191,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@786ccf45
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8460499160 bytes (8068 MB) / 9664200704 bytes (9216 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m -Xms8192m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA0} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['bendicott06'/777, l='tc beta', x=191.10, y=64.00, z=214.98]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by sabrael** [comment]
Downgraded baubles to 1.10.2-1.3.4 and got the same.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 1/15/18 4:17 PM
Description: Ticking player

java.lang.NoSuchMethodError: baubles.api.BaublesApi.isBaubleEquipped(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/item/Item;)I
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 785
	Entity Name: bendicott06
	Entity's Exact location: -170.48, 78.00, 275.19
	Entity's Block location: World: (-171,78,275), Chunk: (at 5,4,3 in -11,17; contains blocks -176,0,272 to -161,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@cbe7f03
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7132266256 bytes (6801 MB) / 9664200704 bytes (9216 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12288m -Xms256m -XX:PermSize=256m -Xms8192m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Forge{12.18.3.2511} [Minecraft Forge] (forge-1.10.2-12.18.3.2511.jar) 
	UCHIJAAAA	Baubles{1.3.4} [Baubles] (Baubles-1.10.2-1.3.4.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA0} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA0.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['bendicott06'/785, l='tc beta', x=-170.48, y=78.00, z=275.19]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Azanor** [comment]
You need to use the latest 1.10.2 version of Baubles
