### ISSUE TITLE
Ticking player crash (baubles)

### ISSUE THREAD

**Issue by fingersome** [Azanor/thaumcraft-beta#72]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  LoadingPlugin (HardcoreDarkness-MC1.10.2-1.9.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  AppleCore (AppleCore-mc1.10.2-3.0.0.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 1/15/18 11:04 PM
Description: Ticking player

java.lang.NoSuchMethodError: baubles.api.BaublesApi.isBaubleEquipped(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/item/Item;)I
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.lib.events.PlayerEvents.pickupXP(PlayerEvents.java:437)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_PlayerEvents_pickupXP_PlayerPickupXpEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.item.EntityXPOrb.func_70100_b_(EntityXPOrb.java:211)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 264
	Entity Name: Fingersome
	Entity's Exact location: 10.74, 90.05, 306.91
	Entity's Block location: World: (10,90,306), Chunk: (at 10,5,2 in 0,19; contains blocks 0,0,304 to 15,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4f42be55
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 605391504 bytes (577 MB) / 2227699712 bytes (2124 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2488 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2488.jar) 
	UCHIJAAAA	Forge{12.18.3.2488} [Minecraft Forge] (forge-1.10.2-12.18.3.2488.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	AppleCore{3.0.0} [AppleCore] (AppleCore-mc1.10.2-3.0.0.jar) 
	UCHIJAAAA	appleskin{1.0.9} [AppleSkin] (AppleSkin-mc1.10.2-1.0.9.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJAAAA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cofhcore{4.1.12} [CoFH Core] (CoFHCore-1.10.2-4.1.12.17-universal.jar) 
	UCHIJAAAA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.7-universal.jar) 
	UCHIJAAAA	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.10-1.1.2.jar) 
	UCHIJAAAA	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCHIJAAAA	endmetals{1.0.4} [End Metals] (EndMetals_1.9-1.0.4.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forgelin{1.6.0} [Shadowfacts' Forgelin] (Forgelin-1.6.0.jar) 
	UCHIJAAAA	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UCHIJAAAA	hardcoredarkness{1.9} [Hardcore Darkness] (HardcoreDarkness-MC1.10.2-1.9.jar) 
	UCHIJAAAA	hopperducts{1.4.8.1} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.1.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.5.2} [JourneyMap] (journeymap-1.10.2-5.5.2.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.2-1.13.jar) 
	UCHIJAAAA	nethermetals{1.1.4} [Nether Metals] (NetherMetals-1.10.2-1.1.4.jar) 
	UCHIJAAAA	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJAAAA	stg{1.0.2} [SwingThroughGrass] (stg-1.0.2.jar) 
	UCHIJAAAA	thaumcraft{6.0.BETA0} [Thaumcraft] (Thaumcraft-1.10.2-6.0.BETA0.jar) 
	UCHIJAAAA	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UCHIJAAAA	thirstybottles{1.0.1.0} [Thirsty Bottles] (ThirstyBottles-1.10.2-1.0.1.0.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
LoadingPlugin (HardcoreDarkness-MC1.10.2-1.9.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.10.2-3.0.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Fingersome'/264, l='Test World', x=10.74, y=90.05, z=306.91]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by fingersome** [comment]
I'm assuming this is to do with the new bauble (headband of curiosity)

**Comment by Azanor** [comment]
You need the latest version of baubles (1.3.13)

**Comment by fingersome** [comment]
ah okay

**Comment by Mii1128** [comment]
Then make thaumcraft require the newer version maybe? Also you might want to update the Baubles version in the Beta folder
