### ISSUE TITLE
Banner Symbols not persisting 

### ISSUE THREAD

**Issue by Xules01** [Azanor/thaumcraft-beta#727]
Thaumcraft-1.12.2-6.1.BETA12
Thaumcraft-1.12.2-6.1.BETA13

After using the phials to place arcane symbols on my banners I find they are lost when I disconnect from the server and reconnect. 

When I tested this on a single player world, it worked fine.

update:  After checking with other players on the server, they can not see the symbols even after I placed them, so it looks like the server is not sending that information to the clients.

**Comment by DarcClan** [comment]
Also having this issues as well with banners not keeping or showing to other players what symbol is placed on the banner

**Comment by Xules01** [comment]
I tried testing this with b19 first, and was getting an error on the server console.  I rolled back to b18 and was able to place the symbols on the banners.

[15:40:14] [Server thread/INFO] [minecraft/DedicatedServer]: [Xules: Given [Phial of Essentia] * 1 to Xules]
[15:40:18] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_193350_e()I
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.EnumDyeColor.func_193350_e()I
        at thaumcraft.common.tiles.misc.TileBanner.getColor(TileBanner.java:73) ~[TileBanner.class:?]
        at thaumcraft.common.blocks.basic.BlockBannerTC.func_180639_a(BlockBannerTC.java:104) ~[BlockBannerTC.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
