### ISSUE TITLE
Banner crash

### ISSUE THREAD

**Issue by purpleposeidon** [Azanor/thaumcraft-beta#766]
Might be caused by dying & respawning near a banner, but isn't consistent.
```
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to thaumcraft.common.blocks.basic.BlockBannerTC
	at thaumcraft.common.tiles.misc.TileBanner.getColor(TileBanner.java:71)
	at thaumcraft.client.renderers.tile.TileBannerRenderer.renderTileEntityAt(TileBannerRenderer.java:35)
	at thaumcraft.client.renderers.tile.TileBannerRenderer.func_192841_a(TileBannerRenderer.java:93)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:155)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:130)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:705)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
```

**Comment by LemADEC** [comment]
Issue is reproduced with Thaumcraft-1.12.2-6.1.BETA16, on a server, while breaking a Thaumcraft banner.
It's fairly intermittent.

It's also reproduced in single player, in the server thread.
```
[01:30:15] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to thaumcraft.common.blocks.basic.BlockBannerTC
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
Caused by: java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to thaumcraft.common.blocks.basic.BlockBannerTC
	at thaumcraft.common.tiles.misc.TileBanner.getColor(TileBanner.java:71) ~[TileBanner.class:?]
	at thaumcraft.common.blocks.basic.BlockBannerTC.func_180657_a(BlockBannerTC.java:185) ~[BlockBannerTC.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```
Here's the list of mods during that occurrence:
```
advancedcombat-1.1.2-[1.12].jar
AIImprovements-1.12-0.0.1b3.jar
AoV-1.12-0.8.13.jar
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv5-stable-11.jar
AttributeFix-1.12.2-1.0.1.jar
Baubles-1.12-1.5.2.jar
baubley-heart-canisters-1.12.2-1.1.1.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterFps-1.4.8.jar
Bookshelf-1.12.2-2.3.550.jar
Born In A Barn V1.8-1.12-1.0.jar
Caliper-1.12.2-1.1.35.jar
Cannibalism-5.1.3-1.12.2.jar
CLib-1.0.2.31-universal.jar
CodeChickenLib-1.12.2-3.1.9.344-universal.jar
CoFHCore-1.12.2-4.5.2.19-universal.jar
FastWorkbench-1.12.2-1.5.0.jar
foamfix-0.9.9.1-1.12.2-anarchy.jar
Guide-API-1.12-2.1.5-60.jar
Guidebook-1.12.2-2.5.0.jar
gigaherz.commons-1.12.1-0.6.4.jar
Hwyla-1.8.26-B41_1.12.2.jar
incontrol-1.12-3.8.0.jar
inventorysorter-1.12.2-1.13.3+57.jar
jei_1.12.2-4.10.0.198.jar
Mantle-1.12-1.3.2.24.jar
MmmMmmMmmMmm-1.12-1.14.jar
MouseTweaks-2.8-mc1.12.1.jar
Passive Aggression-1.12.2-0.0.1.jar
randompatches-1.12.2-1.2.0.0.jar
reauth-3.6.0.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
ShadowMC-1.12-3.8.0.jar
Snad-1.12.1-1.7.09.16a.jar
subcommonlib-sublib-1.12.2-1.2.0.4.jar
TamModized-1.12.1-0.15.5.jar
Thaumcraft-1.12.2-6.1.BETA16.jar
WailaHarvestability-mc1.12-1.1.12.jar
Wawla-1.12.2-2.5.257.jar
```
