### ISSUE TITLE
The Server still crashes upon being upgrade from B13 to B14, crash persists

### ISSUE THREAD

**Issue by peijie7788** [Azanor/thaumcraft-beta#841]
I don't know if it's essentially the same as #836 but my crash report is different:

[15:38:54] [Thread-18/INFO] [THAUMCRAFT]: Starting aura thread for dim 2
[15:38:54] [Forestry Greenhouse/INFO] [forestry]: Starting greenhouse thread
[15:38:54] [Thread-19/INFO] [THAUMCRAFT]: Starting aura thread for dim -1
[15:38:54] [Thread-20/INFO] [THAUMCRAFT]: Starting aura thread for dim 1
[15:38:54] [Thread-21/INFO] [THAUMCRAFT]: Starting aura thread for dim -2
[15:38:54] [Thread-22/INFO] [THAUMCRAFT]: Starting aura thread for dim 0
[15:38:54] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Load CachedWorldData 'lightnetwork' for world 0
[15:38:54] [Server thread/INFO] [Astral Sorcery]: [AstralSorcery] Loading of 'lightnetwork' for world 0 finished.
[15:38:54] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[15:38:54] [Server thread/INFO] [FML]: Unloading dimension -1
[15:38:54] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 1
[15:38:54] [Server thread/INFO] [FML]: Unloading dimension 1
[15:38:54] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -2
[15:38:54] [Server thread/INFO] [FML]: Unloading dimension -2
[15:38:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_171]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_171]
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290) ~[ol.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[15:38:54] [Server thread/WARN] [enderio]: @Devs: See github for dev env setup; set INDEV if needed.
[15:38:54] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\pijie\Desktop\magic1\.\crash-reports\crash-2018-05-23_15.38.54-server.txt
[15:38:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[15:38:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[15:38:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[15:38:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/overworld
[15:38:55] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'world'/Storage Cell
[15:38:55] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[15:38:55] [Thread-22/WARN] [THAUMCRAFT]: AURAS TAKING 117 ms LONGER THAN NORMAL IN DIM 0
[15:38:55] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 2
[15:38:55] [Server thread/INFO] [FML]: Unloading dimension 0
[15:38:55] [Server thread/INFO] [FML]: Unloading dimension 2
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Cannot Hotload Dim: Overworld is not Loaded!
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.common.DimensionManager.initDimension(DimensionManager.java:232)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:830)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at thaumcraft.proxies.ServerProxy.getWorld(ServerProxy.java:18)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at thaumcraft.common.world.aura.AuraWorld.getAuraChunkAt(AuraWorld.java:35)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at thaumcraft.common.world.aura.AuraWorld.getAuraChunkAt(AuraWorld.java:29)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at thaumcraft.common.world.aura.AuraThread.processAuraChunk(AuraThread.java:111)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at thaumcraft.common.world.aura.AuraThread.run(AuraThread.java:66)
[15:38:55] [Thread-22/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Thread.run(Unknown Source)
[15:38:55] [Server thread/INFO] [FML]: Applying holder lookups
[15:38:55] [Server thread/INFO] [FML]: Holder lookups applied
[15:38:55] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[15:38:55] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[15:38:55] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[15:38:55] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

**Comment by katzenpapst** [comment]
Can confirm this. Happens for me as well.

**Comment by AnrDaemon** [comment]
Can you please confirm that it is only caused by upgrade, or also happens when you start a new world with b14?

**Comment by nop277** [comment]
I get the same thing, I haven't tried it with a server but I do know you can create a new world in singleplayer and it will work. When I get home I can try and start a new server world and see what happens. Also I did just switch back to B13 and it fixed the problem if anyone was wondering.

**Comment by katzenpapst** [comment]
In addition to what peijie7788 posted, my log is also full of stuff like this:

```
[21:22:51] [Thread-16/WARN] [FML]: Thaumcraft loaded a new chunk [-98, 31] in dimension 7 (twilight_forest) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-16/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-16/WARN] [FML]: Thaumcraft loaded a new chunk [-98, 30] in dimension 7 (twilight_forest) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-16/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-62, -36] in dimension 0 (overworld) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-63, -36] in dimension 0 (overworld) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-64, -35] in dimension 0 (overworld) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-55, -36] in dimension 0 (overworld) while populating chunk [-55, -18], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-108, 1] in dimension 0 (overworld) while populating chunk [-57, -22], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-108, 17] in dimension 0 (overworld) while populating chunk [-56, -22], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-108, 18] in dimension 0 (overworld) while populating chunk [-56, -22], causing cascading worldgen lag.
[21:22:51] [Thread-19/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[21:22:51] [Thread-19/WARN] [FML]: Thaumcraft loaded a new chunk [-94, -20] in dimension 0 (overworld) while populating chunk [-56, -22], causing cascading worldgen lag.
```

It looks to me like an unchecked recursion of sorts, where Thaumcraft does something to a chunk, which generates it's neighbours, which then prompts Thaumcraft to do the same thing on them, which then generate their neighbours, etc...

**Comment by Ragnarok96** [comment]
Can confirm this is also happening for me! it took me ages to figure out why my server would not start as nothing was directly pointing to thaumcraft. Here is a crash report.

Reverting thaumcraft to B13 caused the server to boot correctly and the crash not to happen.

[latest.log](https://github.com/Azanor/thaumcraft-beta/files/2033066/latest.log)
[crash-2018-05-23_22.51.07-server.txt](https://github.com/Azanor/thaumcraft-beta/files/2033067/crash-2018-05-23_22.51.07-server.txt)

**Comment by Lukas45** [comment]
Can also confirm it happens on a brand new world, in a standalone.
https://pastebin.com/wvLEy4mu
This is an entirely new world

**Comment by Jeffel** [comment]
Also occurs on my server, being upgraded from B13 to B14.
