### ISSUE TITLE
 [TC6.1-B15] Creating blocks with Salis Mundus crashes the game

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-beta#865]
Tested with creating arcance workbench and thaumatorium. i suspect with affects all other similar things, too.
My suspicion is that this is related to https://github.com/Azanor/thaumcraft-beta/issues/863 and that the issue is the sparkle effect spawned by using salis mundus/shown by the thaumometer when looking at unscanned blocks.

<details><summary>Crashlog when creating the arcane workbench:</summary>
<p>
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 5/24/18 9:50 PM
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MalkContent'/1124, l='MpServer', x=196.60, y=73.00, z=252.82]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (196,64,252), Chunk: (at 4,4,12 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1659 game time, 1659 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 103 total; [EntitySkeleton['Skeleton'/4106, l='MpServer', x=259.50, y=43.00, z=325.50], EntityCreeper['Creeper'/4129, l='MpServer', x=275.49, y=34.00, z=193.18], EntityCreeper['Creeper'/4130, l='MpServer', x=276.50, y=34.00, z=192.50], EntityChicken['Chicken'/67, l='MpServer', x=134.50, y=77.00, z=177.50], EntityChicken['Chicken'/68, l='MpServer', x=134.50, y=77.00, z=177.50], EntityChicken['Chicken'/69, l='MpServer', x=126.80, y=76.00, z=181.49], EntityChicken['Chicken'/70, l='MpServer', x=131.50, y=76.00, z=178.63], EntityChicken['Chicken'/79, l='MpServer', x=136.50, y=71.00, z=258.50], EntityChicken['Chicken'/80, l='MpServer', x=137.50, y=70.00, z=258.50], EntityChicken['Chicken'/81, l='MpServer', x=136.50, y=71.00, z=258.50], EntityChicken['Chicken'/82, l='MpServer', x=137.50, y=71.00, z=263.50], EntityCow['Cow'/95, l='MpServer', x=181.66, y=65.00, z=314.48], EntityCow['Cow'/96, l='MpServer', x=180.65, y=65.00, z=314.46], EntityCow['Cow'/97, l='MpServer', x=179.58, y=65.00, z=315.55], EntityCow['Cow'/98, l='MpServer', x=183.50, y=66.00, z=308.50], EntityChicken['Chicken'/99, l='MpServer', x=202.50, y=77.00, z=242.84], EntityChicken['Chicken'/100, l='MpServer', x=208.34, y=72.28, z=261.22], EntityChicken['Chicken'/101, l='MpServer', x=209.49, y=76.00, z=234.10], EntityChicken['Chicken'/102, l='MpServer', x=201.41, y=75.00, z=265.82], EntityChicken['Chicken'/103, l='MpServer', x=202.50, y=63.00, z=177.50], EntityChicken['Chicken'/104, l='MpServer', x=204.46, y=63.00, z=186.15], EntityChicken['Chicken'/105, l='MpServer', x=202.50, y=63.00, z=177.50], EntityChicken['Chicken'/106, l='MpServer', x=203.50, y=63.00, z=176.50], EntityPig['Pig'/107, l='MpServer', x=217.50, y=63.00, z=196.50], EntityChicken['Chicken'/108, l='MpServer', x=228.50, y=69.00, z=283.50], EntityChicken['Chicken'/109, l='MpServer', x=231.50, y=69.00, z=283.50], EntityChicken['Chicken'/110, l='MpServer', x=231.50, y=69.00, z=281.50], EntityChicken['Chicken'/111, l='MpServer', x=231.50, y=68.00, z=284.50], EntityChicken['Chicken'/112, l='MpServer', x=244.26, y=74.00, z=219.86], EntityChicken['Chicken'/113, l='MpServer', x=236.50, y=74.00, z=230.50], EntityChicken['Chicken'/114, l='MpServer', x=239.50, y=74.00, z=229.50], EntityChicken['Chicken'/115, l='MpServer', x=243.50, y=73.00, z=230.50], EntityChicken['Chicken'/116, l='MpServer', x=235.50, y=73.00, z=237.50], EntityChicken['Chicken'/117, l='MpServer', x=232.50, y=73.00, z=235.50], EntityChicken['Chicken'/118, l='MpServer', x=237.50, y=68.00, z=287.50], EntityChicken['Chicken'/119, l='MpServer', x=238.50, y=68.00, z=284.50], EntityChicken['Chicken'/120, l='MpServer', x=228.54, y=67.00, z=293.49], EntityChicken['Chicken'/121, l='MpServer', x=237.50, y=67.00, z=289.50], EntityChicken['Chicken'/123, l='MpServer', x=250.49, y=66.00, z=287.81], EntityChicken['Chicken'/124, l='MpServer', x=248.50, y=66.00, z=292.50], EntityChicken['Chicken'/125, l='MpServer', x=238.81, y=65.00, z=293.50], EntityChicken['Chicken'/126, l='MpServer', x=250.50, y=66.00, z=292.50], EntityCreeper['Creeper'/4258, l='MpServer', x=169.50, y=53.00, z=288.50], EntitySkeleton['Skeleton'/4328, l='MpServer', x=176.50, y=39.00, z=209.50], EntitySkeleton['Skeleton'/4335, l='MpServer', x=265.50, y=46.00, z=209.50], EntityZombie['Zombie'/4714, l='MpServer', x=243.50, y=22.00, z=263.50], EntityCreeper['Creeper'/4805, l='MpServer', x=143.50, y=15.00, z=233.50], EntitySkeleton['Skeleton'/5053, l='MpServer', x=256.50, y=32.00, z=291.50], EntityCreeper['Creeper'/5054, l='MpServer', x=199.50, y=31.00, z=189.50], EntityCreeper['Creeper'/5057, l='MpServer', x=198.50, y=31.00, z=188.50], EntityCreeper['Creeper'/5062, l='MpServer', x=177.50, y=49.00, z=185.50], EntityItem['item.tile.sapling_greatwood'/5098, l='MpServer', x=234.74, y=88.00, z=190.80], EntityBat['Bat'/5138, l='MpServer', x=243.85, y=24.67, z=182.25], EntityBat['Bat'/5185, l='MpServer', x=215.67, y=54.45, z=230.84], EntityZombie['Zombie'/5248, l='MpServer', x=185.50, y=37.00, z=298.50], EntityZombie['Zombie'/5254, l='MpServer', x=223.50, y=61.00, z=278.50], EntityZombie['Zombie'/5255, l='MpServer', x=243.50, y=38.00, z=242.50], EntityZombie['Zombie'/5287, l='MpServer', x=144.50, y=23.00, z=261.50], EntityBat['Bat'/5301, l='MpServer', x=194.27, y=38.32, z=205.76], EntityZombie['Zombie'/5325, l='MpServer', x=202.50, y=34.00, z=279.50], EntityZombieVillager['Zombie Villager'/5348, l='MpServer', x=188.50, y=41.00, z=283.50], EntitySpider['Spider'/5373, l='MpServer', x=222.30, y=23.10, z=210.30], EntitySkeleton['Skeleton'/5412, l='MpServer', x=236.50, y=49.00, z=200.50], EntitySkeleton['Skeleton'/5413, l='MpServer', x=245.50, y=52.00, z=306.50], EntityZombie['Zombie'/5417, l='MpServer', x=233.50, y=18.00, z=297.50], EntitySkeleton['Skeleton'/5421, l='MpServer', x=179.50, y=37.00, z=284.50], EntityCreeper['Creeper'/5422, l='MpServer', x=179.50, y=37.00, z=283.50], EntityCreeper['Creeper'/5423, l='MpServer', x=176.50, y=37.00, z=283.50], EntityCreeper['Creeper'/5488, l='MpServer', x=133.47, y=20.00, z=209.81], EntityZombie['Zombie'/5547, l='MpServer', x=235.74, y=46.00, z=203.52], EntitySkeleton['Skeleton'/5566, l='MpServer', x=122.50, y=49.00, z=216.50], EntitySkeleton['Skeleton'/5573, l='MpServer', x=234.50, y=43.00, z=238.50], EntitySkeleton['Skeleton'/5574, l='MpServer', x=234.50, y=43.00, z=240.50], EntityZombie['Zombie'/5616, l='MpServer', x=222.50, y=49.00, z=192.50], EntityZombie['Zombie'/5617, l='MpServer', x=220.50, y=49.00, z=190.50], EntityCreeper['Creeper'/5618, l='MpServer', x=230.50, y=49.00, z=195.50], EntitySkeleton['Skeleton'/5659, l='MpServer', x=206.50, y=50.00, z=178.68], EntitySkeleton['Skeleton'/5660, l='MpServer', x=209.50, y=50.00, z=186.50], EntityBat['Bat'/5693, l='MpServer', x=261.47, y=48.94, z=235.29], EntityBat['Bat'/5696, l='MpServer', x=265.54, y=47.07, z=214.68], EntityBat['Bat'/5733, l='MpServer', x=132.25, y=21.10, z=205.48], EntityBat['Bat'/5735, l='MpServer', x=226.85, y=17.95, z=196.35], EntitySkeleton['Skeleton'/5762, l='MpServer', x=121.50, y=27.00, z=233.50], EntityZombie['Zombie'/5781, l='MpServer', x=242.50, y=28.00, z=186.50], EntityZombie['Zombie'/5782, l='MpServer', x=235.76, y=27.00, z=192.45], EntityCreeper['Creeper'/5805, l='MpServer', x=195.50, y=45.00, z=187.50], EntitySkeleton['Skeleton'/5816, l='MpServer', x=198.50, y=32.00, z=300.50], EntityCreeper['Creeper'/5817, l='MpServer', x=199.50, y=32.00, z=301.50], EntityCreeper['Creeper'/5818, l='MpServer', x=200.50, y=32.00, z=298.50], EntitySquid['Squid'/5830, l='MpServer', x=256.38, y=61.42, z=234.58], EntitySquid['Squid'/5831, l='MpServer', x=251.92, y=61.63, z=236.98], EntitySquid['Squid'/5832, l='MpServer', x=252.46, y=62.52, z=235.20], EntityWitch['Witch'/5881, l='MpServer', x=257.50, y=48.00, z=234.50], EntityWitch['Witch'/5882, l='MpServer', x=262.50, y=48.00, z=234.50], EntitySkeleton['Skeleton'/5910, l='MpServer', x=148.50, y=13.00, z=228.50], EntityCreeper['Creeper'/5931, l='MpServer', x=262.50, y=49.00, z=226.50], EntityBat['Bat'/2134, l='MpServer', x=260.59, y=50.23, z=231.13], EntityPlayerSP['MalkContent'/1124, l='MpServer', x=196.60, y=73.00, z=252.82], EntitySkeleton['Skeleton'/3884, l='MpServer', x=189.50, y=38.00, z=191.50], EntityItem['item.tile.gravel'/3986, l='MpServer', x=252.25, y=22.00, z=277.93], EntityItem['item.tile.gravel'/3987, l='MpServer', x=251.13, y=22.00, z=278.45], EntityBat['Bat'/4050, l='MpServer', x=153.45, y=43.32, z=284.58], EntityBat['Bat'/4052, l='MpServer', x=249.39, y=48.59, z=205.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2738)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3432795128 bytes (3273 MB) / 4160749568 bytes (3968 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 10 total; -Xmx8192m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2702 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID         | Version      | Source                           | Signature                                |
	|:--------- |:---------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft  | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp        | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML        | 8.0.99.99    | forge-1.12.2-14.23.3.2702.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge      | 14.23.3.2702 | forge-1.12.2-14.23.3.2702.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | baubles    | 1.5.2        | Baubles-1.12-1.5.2.jar           | None                                     |
	| UCHIJAAAA | jei        | 4.9.1.188    | jei_1.12.2-4.9.1.188.jar         | None                                     |
	| UCHIJAAAA | journeymap | 1.12.2-5.5.2 | journeymap-1.12.2-5.5.2.jar      | None                                     |
	| UCHIJAAAA | thaumcraft | 6.1.BETA15   | Thaumcraft-1.12.2-6.1.BETA15.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.01' Renderer: 'GeForce GTX 980/PCIe/SSE2'
	Launched Version: forge-14.23.3.2702
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 

</p>
</details>

JourneyMap x5.5.2
JEI x188
TC6.1-B15
forge x2702

**Comment by AnrDaemon** [comment]
I only logged into game. Probably had some items on display on the pedestals, but nothing in hand or what not, that I recall.

https://gist.github.com/AnrDaemon/825e5ee5aa768aef27b505e6489b2b5b

**Comment by Sumguy62** [comment]
This is anything that creates particles. Even going through a nether portal crashes the game.

**Comment by enderger** [comment]
For me, the bug occurs in B14

**Comment by enderger** [comment]
This bug may be a sife effect of decreasing lag when using the thuamometer
