### ISSUE TITLE
[B15] crash when creating the Thaumonomicon

### ISSUE THREAD

**Issue by Shandoo94** [Azanor/thaumcraft-beta#878]
My game crashes with following error, when i create the Thaumonomicon with salismundus on a bookshelf:

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_318_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Geethebluesky** [comment]
This is another form of the same bug everyone else is seeing, try playing on Beta 14, if you're on a server it may not work.

**Comment by yunruiwatts** [comment]
Duplicate of #858
