### ISSUE TITLE
New Crash Beta 15

### ISSUE THREAD

**Issue by Orncaex** [Azanor/thaumcraft-beta#879]
Ok so I download beta 15, load world, every thing is fine, night rolls around so i go to scan the sky, get the moon scaned, pan over  to the next target and my Scanner lands on my Astral Sorcery Altar which I have not scanned aparently and it instantly crashes. Reloaded 3 times, crashed right away. I downgrade the version to 14 to find out that i had not scanned the altar before and did so.... May be a partical issue but i cant read error codes very well

11:04:18 | net.minecraft.client.Minecraft | Unreported exception thrown! java.lang.UnsupportedOperationException 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176) 	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_149_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- | -- | --

**Comment by Geethebluesky** [comment]
Please use search, there are multiple reports for the same issue you're seeing.

Going back to Beta 14 may help unless you're running a server.

**Comment by Orncaex** [comment]
New to github. Also dont know how to search for this exact problem so... hey it might be unique. I dont know. I dont know code but as far as i can tell its... Particles. I dont understand how that would or could crash a game

**Comment by Geethebluesky** [comment]
Enter "crash" in the searchbar above the issues list, you won't know if it's unique unless you search first. It's a known issue affecting a lot of people.

**Comment by yunruiwatts** [comment]
Duplicate of #858

**Comment by Orncaex** [comment]
Cool I'll keep that in mind
