### ISSUE TITLE
(Not a bug) Reminding you to not repert bug #858 over and over again 

### ISSUE THREAD

**Issue by enderger** [Azanor/thaumcraft-beta#884]
I know that you are crashing, but that bug has been reported as bug #858. Please reply to the issue there.

**Comment by yunruiwatts** [comment]
If you're running B15 and it crashes, you should assume it's because of the bug that's already been reported.

If for some reason you think it's not, make sure `UnsupportedOperationException` is not in the crash log. It should be in a context like this:

    java.lang.UnsupportedOperationException
        at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)
        at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)

**Comment by Geethebluesky** [comment]
Issue templates, anyone?

[https://github.com/Azanor/thaumcraft-suggestions/issues/290](https://github.com/Azanor/thaumcraft-suggestions/issues/290)

**Comment by enderger** [comment]
This is just telling people to not report B15 crashes, as the number of reports on that issue is problematic

**Comment by Geethebluesky** [comment]
This specific issue, yes. But lots of people come over here to make their very first Github report in this repo, they can learn to help themselves; plus more than just this bug has re-submissions, like the Pech kept being submitted over and over too.

**Comment by enderger** [comment]
Ok

**Comment by enderger** [comment]
That would probably be a better topic for this issue

**Comment by yunruiwatts** [comment]
Also seems like Azanor could use some help managing issues, but I don't think there's a way to grant only permission to manage issues.

**Comment by enderger** [comment]
Thaumcraft’s code is not on github, so people only could change the readmes

**Comment by Geethebluesky** [comment]
Managing issues may be limited to marking things as duplicate though (which is most of the work it seems!), or that'll mess up his workflow.

**Comment by enderger** [comment]
Can someone pin this issue so that people will notice and not post it out of the way? People need to see that they should not duplicate bug reports.

**Comment by Geethebluesky** [comment]
Azanor'll have to be the one deciding on how to proceed since no one else has permissions to this repo AFAIK. He does updates in batches so whenever he comes back around.
