### ISSUE TITLE
Got a crash Report to deliver. 

### ISSUE THREAD

**Issue by Convergence2738** [Azanor/thaumcraft-beta#896]
I looked over the crash report and it narrowed down to a issue with a particle generation in the magical Forest biome. I crashed as I entered the biome, and the crash persists on load. 

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_216_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Here is the more detailed section 
The stack trace:
Stacktrace:
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_216_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)

Hope this helps you squash those bugs. (that is, if this a bug that happens to others)

**Comment by Geethebluesky** [comment]
Please use search before reporting issues: duplicate of #858
