### ISSUE TITLE
[Thaumcraft-1.12.2-6.1.BETA15] Random Seeming crash in overworld

### ISSUE THREAD

**Issue by Seth0067** [Azanor/thaumcraft-beta#902]
I really was doing nothing more than looking at mossy stone when this happened.  

Pack includes many texh mods, Mcjty's lost cities, among others.

Exciting, [huh?]

(https://pastebin.com/ESD4YtAB)

**Comment by Lukas45** [comment]
Same crash as #858, broken render engine

**Comment by theCoosome** [comment]
Same- a particle related crash with Thaumcraft. Still occurred after disabling all but baubles and Thaumcraft.

Crashes my game every time on loading into my world after updating from beta 13 if that helps.
Always the same error on the same line, may want to check out thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296).


16:37:51 | THAUMCRAFT | No auras found!
-- | -- | --
16:37:51 | net.minecraft.client.Minecraft | Unreported exception thrown! java.lang.UnsupportedOperationException 	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176) 	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_64_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343) 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
