### ISSUE TITLE
[Beta 15] Crash when wearing goggles in baubles slot.

### ISSUE THREAD

**Issue by shuuichikun** [Azanor/thaumcraft-beta#916]
Forge version 14.23.2697.

Running Beta 15, I was able to start my server successfully, as well as load single player client. upon logging onto a server which I previously had beta 13 installed, I instantly got a crash. In single player this was not a problem. However, the main difference I noted was the existence of the goggles in the baubles slot and the thaumometer in the player inventory. I'll do more thorough testing to see if it's the thaumometer or the goggles, once I get more time. I wanted to make note of it in case someone hasn't stumbled on this issue yet. (There were other mods installed, but rolling back to beta 13 fixed the issue instantly, I can get a full list of mods if needed.)

Server side read: 

30.05 13:43:15 [Disconnect] User [net.minecraft.network.NetHandlerPlayServer]: shuuichikun has disconnected, reason: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

Will get crash logs and add in pastebin once I get to a place that I can.

**Comment by wamc2017** [comment]
Have a look into your client crash-log and post it on pastebin or gist.

Beta 15 is known for crashing because of some bug by rendering particles, if the log says something like this: `java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(Unknown Source)` it's a dupe of #858 and you don't need to report it again (because there are many duplicates on this tracker reporting the same problem...)

Best bet is to downgrade to beta 14 (or beta 13 if you're playing on a server...) until this bug is fixed...

**Comment by shuuichikun** [comment]
Yep, looks like that was the issue.

For posterity:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  RandomPatches (randompatches-1.12.2-1.1.0.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.169.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/30/18 1:43 PM
Description: Unexpected error

java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1176)
	at thaumcraft.client.fx.ParticleEngine.updateParticles(ParticleEngine.java:296)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
