### ISSUE TITLE
Stabilizer crashes server

### ISSUE THREAD

**Issue by FanghanHu** [Azanor/thaumcraft-beta#969]
Using thaumcraft 6 beta 16
I have a infusion altar and a stabilizer pointed at it from above.
Server crashed, after restart, server crashes as soon as i login.

Here is the crash log

```
06.06 03:25:05 [Server] Server thread/ERROR Encountered an unexpected exception
06.06 03:25:05 [Server] INFO net.minecraft.util.ReportedException: Exception ticking world
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:762) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
06.06 03:25:05 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
06.06 03:25:05 [Server] INFO at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122) ~[TileStabilizer.class:?]
06.06 03:25:05 [Server] INFO at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82) ~[BlockTCTile.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO ... 4 more
06.06 03:25:05 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
06.06 03:25:05 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122) ~[TileStabilizer.class:?]
06.06 03:25:05 [Server] INFO at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82) ~[BlockTCTile.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO ... 4 more
06.06 03:25:05 [Server] INFO Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6f6a7463 from coremod FMLCorePlugin
06.06 03:25:05 [Server] INFO at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
06.06 03:25:05 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
06.06 03:25:05 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122) ~[TileStabilizer.class:?]
06.06 03:25:05 [Server] INFO at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82) ~[BlockTCTile.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO ... 4 more
06.06 03:25:05 [Server] INFO Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
06.06 03:25:05 [Server] INFO at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
06.06 03:25:05 [Server] INFO at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258) ~[forge-1.12.2-14.23.4.2705-universal.jar:?]
06.06 03:25:05 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
06.06 03:25:05 [Server] INFO at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
06.06 03:25:05 [Server] INFO at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122) ~[TileStabilizer.class:?]
06.06 03:25:05 [Server] INFO at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82) ~[BlockTCTile.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476) ~[awu$a.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238) ~[oo.class:?]
06.06 03:25:05 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) ~[MinecraftServer.class:?]
06.06 03:25:05 [Server] INFO ... 4 more
```

**Comment by Garogat** [comment]
Is done meaning there is an update?

**Comment by Geethebluesky** [comment]
No, just that it will be present in a future update.

**Comment by FanghanHu** [comment]
Is there any way for me to get back in the server without losing the world?

**Comment by Garogat** [comment]
Just download the world and simply remove the stabilizer block with something like mcedit.

**Comment by OfficialStamper** [comment]
Bounce: I have just got the exact same error on my server. Any ETA on next update please?

**Comment by LawrenceWolf** [comment]
Same here. I was hoping it was fixed since beta14, as there were 2 updates. But I just hooked it up to universal cables, and server crashed instantly.

**Comment by belathus** [comment]
Yeah, I just crashed our server the same way.

**Comment by dragonshardz** [comment]
Fixed in B17
