### ISSUE TITLE
Stabilizer crash

### ISSUE THREAD

**Issue by Tehhatein** [Azanor/thaumcraft-beta#982]
I was trying to make something with the infuser and I had just placed the stabilizer and powered it, as soon as the power got to it the game crashed and I had to go into MCedit to remove it to save the server ( it would not start up after I had powered it ) The error disappears before I can see what it is but i'll try to find it

**Comment by Geethebluesky** [comment]
Possibly a duplicate of #969.

Provide a crash log please (using Pastebin or [Gist](http://gist.github.com)), and make sure you're using Beta 16.

**Comment by red360** [comment]
Same issue.

--- Minecraft Crash Report ----

WARNING: coremods are present:
  AstralCore (astralsorcery-1.12.2-1.8.10.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.7.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b154.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/8/18 4:33 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122)
	at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.Particle
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@c446b14 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 13 more
Caused by: java.lang.RuntimeException: Attempted to load class btf for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at thaumcraft.common.tiles.devices.TileStabilizer.func_145842_c(TileStabilizer.java:122)
	at thaumcraft.common.blocks.BlockTCTile.func_189539_a(BlockTCTile.java:82)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189547_a(BlockStateContainer.java:476)
	at net.minecraft.world.WorldServer.func_147485_a(WorldServer.java:1225)
	at net.minecraft.world.WorldServer.func_147488_Z(WorldServer.java:1212)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:238)

-- Affected level --
Details:
	Level name: ULXMT
	All players: 1 total; [EntityPlayerMP['XRED_360'/527, l='ULXMT', x=-40.61, y=64.33, z=-615.70]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 864314869
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.0-127-generic
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1967783768 bytes (1876 MB) / 4159438848 bytes (3966 MB) up to 4159438848 bytes (3966 MB)
	JVM Flags: 5 total; -Xms4000M -Xmx4000M -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 139 mods loaded, 139 mods active

**Comment by Geethebluesky** [comment]
Guys, use [Gist](http://gist.github.com) or [Pastebin](http://pastebin.com) to post your logs, nobody really likes having to scroll past a huge comment like that.
